const mockGetFirstAsync = jest.fn();
const mockRunAsync = jest.fn();

jest.mock("../sqlite", () => ({
  db: {
    getFirstAsync: (...args: unknown[]) => mockGetFirstAsync(...args),
    runAsync: (...args: unknown[]) => mockRunAsync(...args),
  },
}));

import {
  getMonthlyPlanningBlueprint,
  upsertMonthlyPlanningBlueprint,
} from "../monthly-planning-blueprints";

describe("monthly planning blueprint persistence", () => {
  beforeEach(() => {
    jest.clearAllMocks();
    mockGetFirstAsync.mockResolvedValue(null);
    mockRunAsync.mockResolvedValue(undefined);
  });

  it("reads a blueprint through class, cycle, year and month lineage", async () => {
    await getMonthlyPlanningBlueprint({
      classId: "class_1",
      cycleId: "cycle_1",
      year: 2026,
      month: 7,
    });

    expect(mockGetFirstAsync).toHaveBeenCalledWith(
      expect.stringContaining("cycleId = ?"),
      ["class_1", 2026, 7, "cycle_1"],
    );
  });

  it("persists the complete generation context instead of a transient object", async () => {
    await upsertMonthlyPlanningBlueprint({
      id: "blueprint_1",
      classId: "class_1",
      cycleId: "cycle_1",
      year: 2026,
      month: 7,
      title: "Julho",
      macroIntent: "Fundamentos",
      pedagogicalProgression: "[]",
      weeklyFocusDistributionJson: "{}",
      constraintsJson: "{}",
      contextSnapshotJson: JSON.stringify({ schemaVersion: 2 }),
      generationModelVersion: "planning-v2",
      generationVersion: 2,
      syncStatus: "in_sync",
      lastAutoGeneratedAt: "2026-07-30T00:00:00.000Z",
      lastManualEditedAt: "",
      createdAt: "2026-07-01T00:00:00.000Z",
      updatedAt: "2026-07-30T00:00:00.000Z",
    });

    expect(mockRunAsync).toHaveBeenCalledWith(
      expect.stringContaining("contextSnapshotJson"),
      expect.arrayContaining([
        "cycle_1",
        expect.stringContaining('"schemaVersion":2'),
        "planning-v2",
      ]),
    );
  });
});
