import { Ionicons } from "@expo/vector-icons";
import type { ComponentProps } from "react";

import { decorativeIconProps } from "./decorative-icon-props";

export type IoniconName = ComponentProps<typeof Ionicons>["name"];

export const GOATLETA_ICON_NAMES = {
  home: "home-outline",
  dashboard: "grid-outline",
  classes: "school-outline",
  organization: "business-outline",
  students: "people-outline",
  members: "people-outline",
  planning: "clipboard-outline",
  reports: "stats-chart-outline",
  calendar: "calendar-outline",
  agenda: "today-outline",
  absenceNotices: "notifications-outline",
  notifications: "notifications-outline",
  darkMode: "moon-outline",
  exercises: "book-outline",
  achievements: "ribbon-outline",
  periodization: "trending-up-outline",
  trend: "trending-up",
  regulations: "layers-outline",
  events: "calendar-clear-outline",
  management: "settings-outline",
  communications: "megaphone-outline",
  assistant: "sparkles-outline",
  sparkles: "sparkles",
  profile: "person-outline",
  personSolid: "person",
  profileCircle: "person-circle-outline",
  professor: "school-outline",
  coordination: "briefcase-outline",
  student: "person-outline",
  consultation: "person-outline",
  attendance: "checkmark-done-outline",
  addStudent: "person-add-outline",
  plan: "fitness-outline",
  training: "barbell-outline",
  warmup: "flame-outline",
  mainActivity: "fitness-outline",
  cooldown: "leaf-outline",
  feedback: "chatbox-ellipses-outline",
  scouting: "analytics-outline",
  nfc: "radio-outline",
  radio: "radio",
  chat: "chatbubble-ellipses-outline",
  message: "chatbubble-outline",
  search: "search-outline",
  link: "link-outline",
  open: "open-outline",
  document: "document-text-outline",
  documentAttach: "document-attach-outline",
  edit: "create-outline",
  pencil: "pencil",
  share: "share-social-outline",
  google: "logo-google",
  whatsapp: "logo-whatsapp",
  youtube: "logo-youtube",
  instagram: "logo-instagram",
  vimeo: "logo-vimeo",
  apple: "logo-apple",
  facebook: "logo-facebook",
  camera: "camera-outline",
  compare: "git-compare",
  align: "reorder-three",
  map: "map",
  list: "list-outline",
  biometrics: "finger-print-outline",
  logout: "log-out-outline",
  info: "information",
  engagement: "pulse-outline",
  checklist: "checkmark-done-outline",
  checkmark: "checkmark",
  checkmarkOutline: "checkmark-outline",
  checkmarkCircle: "checkmark-circle",
  success: "checkmark-circle-outline",
  checkbox: "checkbox",
  circle: "ellipse",
  circleOutline: "ellipse-outline",
  square: "square-outline",
  options: "options-outline",
  construct: "construct-outline",
  shield: "shield-checkmark-outline",
  copy: "copy-outline",
  swap: "swap-horizontal-outline",
  swapVertical: "swap-vertical-outline",
  ellipsisHorizontal: "ellipsis-horizontal",
  flash: "flash-outline",
  upload: "cloud-upload-outline",
  download: "cloud-download-outline",
  cloudDone: "cloud-done-outline",
  save: "save-outline",
  sync: "sync-outline",
  refresh: "refresh",
  time: "time-outline",
  view: "eye-outline",
  viewSolid: "eye",
  eyeOff: "eye-off-outline",
  eyeOffSolid: "eye-off",
  trash: "trash-outline",
  play: "play",
  playForward: "play-forward-outline",
  pause: "pause",
  playCircle: "play-circle-outline",
  skipBack: "play-skip-back",
  skipForward: "play-skip-forward",
  repeat: "repeat-outline",
  flag: "flag-outline",
  warning: "alert",
  warningCircle: "alert-circle",
  gift: "gift",
  giftOutline: "gift-outline",
  birthday: "balloon",
  trophy: "trophy",
  star: "star",
  key: "key-outline",
  lock: "lock-closed-outline",
  location: "location",
  arrowForward: "arrow-forward",
  arrowUp: "arrow-up",
  hourglass: "hourglass-outline",
  chevronForwardCircle: "chevron-forward-circle-outline",
  close: "close",
  closeCircle: "close-circle",
  ellipse: "ellipse",
  externalProvider: "globe-outline",
  ellipsisVertical: "ellipsis-vertical",
  add: "add",
  chevronBack: "chevron-back-outline",
  chevronForward: "chevron-forward-outline",
  chevronRight: "chevron-forward",
  chevronUp: "chevron-up-outline",
  chevronDown: "chevron-down-outline",
} as const satisfies Record<string, IoniconName>;

export type GoAtletaIconName = keyof typeof GOATLETA_ICON_NAMES;

type GoAtletaIconProps = Omit<ComponentProps<typeof Ionicons>, "name"> & {
  name: GoAtletaIconName;
};

export function getGoAtletaIconName(name: GoAtletaIconName): IoniconName {
  return GOATLETA_ICON_NAMES[name];
}

export function GoAtletaIcon({ name, ...props }: GoAtletaIconProps) {
  return <Ionicons {...decorativeIconProps} {...props} name={getGoAtletaIconName(name)} />;
}
