// ─────────────────────────────────────────────────────────────────────────────
// Catálogo canônico de progressão pedagógica do voleibol
//
// Cada stage mapeia:
//   ageBand (canônico) → mês → sequência dentro do mês
//   → forma de jogo → skills já introduzidas / contextos já praticados
//   → próximo passo → restrições pedagógicas → blocos recomendados
//   → fonte metodológica rastreável
//
// Regra: nenhum termo estrangeiro (toetsen, cmv niveau, etc.) pode aparecer
// aqui. Use a source.sourceRef apenas para rastreabilidade interna.
// ─────────────────────────────────────────────────────────────────────────────

import type { PedagogicalProgressionStage } from "./pedagogical-types";

type StageSeed = Omit<PedagogicalProgressionStage, "ageBand" | "gameForm" | "source"> & {
  source: PedagogicalProgressionStage["source"];
};

const make08to10Stage = (seed: StageSeed): PedagogicalProgressionStage => ({
  ...seed,
  ageBand: "08-10",
  gameForm: "mini_2x2",
});

const make11to12Stage = (seed: StageSeed): PedagogicalProgressionStage => ({
  ...seed,
  ageBand: "11-12",
  gameForm: "mini_3x3",
});

const make13to14Stage = (seed: StageSeed): PedagogicalProgressionStage => ({
  ...seed,
  ageBand: "13-14",
  gameForm: "mini_4x4",
});

const playfulWarmup = (
  skills: StageSeed["blockRecommendations"]["warmup"]["skills"],
  contexts: StageSeed["blockRecommendations"]["warmup"]["contexts"],
  organization: StageSeed["blockRecommendations"]["warmup"]["organization"] = "dupla"
) => ({
  skills,
  contexts,
  organization,
  taskStyle: "brincadeira" as const,
  intensity: "leve" as const,
});

const guidedMain = (
  skills: StageSeed["blockRecommendations"]["main"]["skills"],
  contexts: StageSeed["blockRecommendations"]["main"]["contexts"],
  taskStyle: StageSeed["blockRecommendations"]["main"]["taskStyle"] = "desafio_curto",
  organization: StageSeed["blockRecommendations"]["main"]["organization"] = "equipes_reduzidas",
  intensity: StageSeed["blockRecommendations"]["main"]["intensity"] = "moderada"
) => ({
  skills,
  contexts,
  organization,
  taskStyle,
  intensity,
});

const closingBlock = (
  skills: StageSeed["blockRecommendations"]["cooldown"]["skills"],
  contexts: StageSeed["blockRecommendations"]["cooldown"]["contexts"]
) => ({
  skills,
  contexts,
  organization: "roda" as const,
  taskStyle: "fechamento" as const,
  intensity: "leve" as const,
});

const STAGES_08_TO_10: PedagogicalProgressionStage[] = [
  make08to10Stage({
    id: "08-10_jan_01",
    monthIndex: 1,
    sequenceIndex: 1,
    phase: "exploracao_motora",
    stageLabel: "familiarização com a bola e controle inicial",
    complexityLevel: "baixo",
    alreadyIntroduced: ["throw_catch_control"],
    alreadyPracticedContexts: ["free_space", "individual_control"],
    nextStep: ["set_self_control", "mini_game_1x1_intro"],
    pedagogicalConstraints: [
      "usar linguagem concreta e direta",
      "priorizar ludicidade sobre técnica",
      "não usar leitura tática abstrata",
    ],
    blockRecommendations: {
      warmup: playfulWarmup(["throw_catch_control"], ["free_space", "individual_control"], "individual"),
      main: guidedMain(["set_self_control", "mini_game_1x1_intro"], ["pair_work", "adapted_rules"], "desafio_curto", "dupla", "leve"),
      cooldown: closingBlock([], []),
    },
    source: {
      methodology: "rede_esperanca",
      sourceLabel: "Rede Esperança — janeiro",
      sourceRef: "controle inicial, lançar/pegar e mini jogo simples",
    },
  }),
  make08to10Stage({
    id: "08-10_jan_02",
    monthIndex: 1,
    sequenceIndex: 2,
    phase: "exploracao_motora",
    stageLabel: "toque inicial com alvo simples",
    complexityLevel: "baixo",
    alreadyIntroduced: ["throw_catch_control", "set_self_control"],
    alreadyPracticedContexts: ["pair_work", "simple_target"],
    nextStep: ["set_target_simple", "mini_game_1x1_intro"],
    pedagogicalConstraints: [
      "organizar em duplas e trios",
      "manter pouco tempo por tarefa",
      "usar alvo visível para a criança",
    ],
    blockRecommendations: {
      warmup: playfulWarmup(["set_self_control"], ["pair_work"]),
      main: guidedMain(["set_target_simple", "mini_game_1x1_intro"], ["simple_target", "adapted_rules"], "estacao", "trio", "leve"),
      cooldown: closingBlock(["set_self_control"], []),
    },
    source: {
      methodology: "instituto_compartilhar",
      sourceLabel: "Mini 2x2 — Compartilhar",
      sourceRef: "toque inicial, alvos visíveis e jogo muito simples",
    },
  }),
  make08to10Stage({
    id: "08-10_jan_03",
    monthIndex: 1,
    sequenceIndex: 3,
    phase: "exploracao_motora",
    stageLabel: "mini jogo muito simples com primeiro envio",
    complexityLevel: "baixo",
    alreadyIntroduced: ["throw_catch_control", "set_self_control", "set_target_simple"],
    alreadyPracticedContexts: ["pair_work", "adapted_rules", "reduced_court"],
    nextStep: ["underhand_serve_intro", "mini_game_1x1_intro"],
    pedagogicalConstraints: [
      "não exigir continuidade longa",
      "manter mini jogo como brincadeira orientada",
      "corrigir um detalhe por vez",
    ],
    blockRecommendations: {
      warmup: playfulWarmup(["throw_catch_control", "set_self_control"], ["pair_work"]),
      main: guidedMain(["underhand_serve_intro", "mini_game_1x1_intro"], ["reduced_court", "adapted_rules"], "mini_jogo", "equipes_reduzidas", "leve"),
      cooldown: closingBlock([], []),
    },
    source: {
      methodology: "rede_esperanca",
      sourceLabel: "Rede Esperança — janeiro",
      sourceRef: "fechamento do mês com envio simples e mini jogo",
    },
  }),
  make08to10Stage({
    id: "08-10_feb_01",
    monthIndex: 2,
    sequenceIndex: 1,
    phase: "fundamentos_basicos",
    stageLabel: "saque por baixo adaptado e alvo simples",
    complexityLevel: "baixo_moderado",
    alreadyIntroduced: ["set_self_control", "set_target_simple", "underhand_serve_intro"],
    alreadyPracticedContexts: ["pair_work", "simple_target", "adapted_rules"],
    nextStep: ["underhand_serve_target", "receive_simple"],
    pedagogicalConstraints: [
      "manter gesto simples e adaptado",
      "usar alvos grandes",
      "não cobrar potência",
    ],
    blockRecommendations: {
      warmup: playfulWarmup(["set_self_control", "underhand_serve_intro"], ["pair_work", "simple_target"]),
      main: guidedMain(["underhand_serve_target", "receive_simple"], ["simple_target", "reduced_court"], "estacao", "dupla"),
      cooldown: closingBlock(["receive_simple"], []),
    },
    source: {
      methodology: "rede_esperanca",
      sourceLabel: "Rede Esperança — fevereiro",
      sourceRef: "saque por baixo adaptado e recepção simples",
    },
  }),
  make08to10Stage({
    id: "08-10_feb_02",
    monthIndex: 2,
    sequenceIndex: 2,
    phase: "fundamentos_basicos",
    stageLabel: "continuidade inicial com 2 ações",
    complexityLevel: "baixo_moderado",
    alreadyIntroduced: ["underhand_serve_target", "receive_simple"],
    alreadyPracticedContexts: ["pair_work", "simple_target", "continuity_game"],
    nextStep: ["two_action_continuity", "mini_game_2x2_intro"],
    pedagogicalConstraints: [
      "falar em continuidade e colega certo",
      "não subir para 3 ações ainda",
      "manter tarefas curtas e claras",
    ],
    blockRecommendations: {
      warmup: playfulWarmup(["receive_simple"], ["pair_work", "continuity_game"]),
      main: guidedMain(["two_action_continuity", "mini_game_2x2_intro"], ["continuity_game", "reduced_court"], "mini_jogo", "equipes_reduzidas"),
      cooldown: closingBlock(["mini_game_2x2_intro"], []),
    },
    source: {
      methodology: "cmv_nederland",
      sourceLabel: "CMV 8-10",
      sourceRef: "continuidade curta e início do 2x2",
    },
  }),
  make08to10Stage({
    id: "08-10_feb_03",
    monthIndex: 2,
    sequenceIndex: 3,
    phase: "fundamentos_basicos",
    stageLabel: "mini 2x2 inicial com colega certo",
    complexityLevel: "baixo_moderado",
    alreadyIntroduced: ["receive_simple", "two_action_continuity", "mini_game_2x2_intro"],
    alreadyPracticedContexts: ["reduced_court", "continuity_game", "adapted_rules"],
    nextStep: ["receive_direction", "mini_game_2x2_continuity"],
    pedagogicalConstraints: [
      "orientar para jogar a primeira bola ao colega",
      "manter quadra reduzida",
      "evitar cobrança tática abstrata",
    ],
    blockRecommendations: {
      warmup: playfulWarmup(["set_target_simple", "receive_simple"], ["pair_work", "simple_target"]),
      main: guidedMain(["receive_direction", "mini_game_2x2_continuity"], ["reduced_court", "application_game"], "mini_jogo", "equipes_reduzidas", "moderada"),
      cooldown: closingBlock([], []),
    },
    source: {
      methodology: "instituto_compartilhar",
      sourceLabel: "Mini 2x2 — Compartilhar",
      sourceRef: "fechamento do mês com colega certo e 2x2 inicial",
    },
  }),
  make08to10Stage({
    id: "08-10_mar_01",
    monthIndex: 3,
    sequenceIndex: 1,
    phase: "consolidacao_ludica",
    stageLabel: "recepção, levantamento à frente e devolução",
    complexityLevel: "moderado",
    alreadyIntroduced: ["receive_direction", "mini_game_2x2_continuity"],
    alreadyPracticedContexts: ["continuity_game", "reduced_court"],
    nextStep: ["lift_front_intro", "two_action_continuity"],
    pedagogicalConstraints: [
      "organizar a sequência com ajuda do professor",
      "dar referência visual de para onde levantar",
      "não cobrar velocidade alta",
    ],
    blockRecommendations: {
      warmup: playfulWarmup(["receive_direction"], ["pair_work", "simple_target"]),
      main: guidedMain(["lift_front_intro", "two_action_continuity"], ["continuity_game", "simple_target"], "estacao", "trio", "moderada"),
      cooldown: closingBlock(["lift_front_intro"], []),
    },
    source: {
      methodology: "rede_esperanca",
      sourceLabel: "Rede Esperança — março",
      sourceRef: "recepção, levantamento e devolução com apoio",
    },
  }),
  make08to10Stage({
    id: "08-10_mar_02",
    monthIndex: 3,
    sequenceIndex: 2,
    phase: "consolidacao_ludica",
    stageLabel: "continuidade com 2 a 3 ações",
    complexityLevel: "moderado",
    alreadyIntroduced: ["lift_front_intro", "two_action_continuity"],
    alreadyPracticedContexts: ["continuity_game", "application_game"],
    nextStep: ["three_action_continuity", "mini_game_2x2_continuity"],
    pedagogicalConstraints: [
      "subir para 3 ações só com apoio do colega",
      "manter linguagem simples e concreta",
      "não transformar em jogo formal",
    ],
    blockRecommendations: {
      warmup: playfulWarmup(["set_with_movement", "receive_direction"], ["pair_work", "continuity_game"]),
      main: guidedMain(["three_action_continuity", "mini_game_2x2_continuity"], ["continuity_game", "reduced_court"], "mini_jogo", "equipes_reduzidas", "moderada"),
      cooldown: closingBlock([], []),
    },
    source: {
      methodology: "rede_esperanca",
      sourceLabel: "Rede Esperança — março",
      sourceRef: "continuidade de 2 a 3 ações com mini jogo",
    },
  }),
  make08to10Stage({
    id: "08-10_mar_03",
    monthIndex: 3,
    sequenceIndex: 3,
    phase: "consolidacao_ludica",
    stageLabel: "mini jogo mais organizado com 2 a 3 ações",
    complexityLevel: "moderado",
    alreadyIntroduced: ["three_action_continuity", "mini_game_2x2_continuity"],
    alreadyPracticedContexts: ["application_game", "reduced_court"],
    nextStep: ["receive_direction", "mini_game_2x2_continuity"],
    pedagogicalConstraints: [
      "dar regra simples para organização",
      "valorizar estabilidade, não velocidade",
      "usar poucos comandos por rodada",
    ],
    blockRecommendations: {
      warmup: playfulWarmup(["receive_direction", "set_with_movement"], ["pair_work"]),
      main: guidedMain(["mini_game_2x2_continuity", "receive_direction"], ["application_game", "reduced_court"], "mini_jogo", "equipes_reduzidas", "moderada"),
      cooldown: closingBlock([], []),
    },
    source: {
      methodology: "instituto_compartilhar",
      sourceLabel: "Mini 2x2 — Compartilhar",
      sourceRef: "mais organização do mini jogo sem salto brusco",
    },
  }),
  make08to10Stage({
    id: "08-10_apr_01",
    monthIndex: 4,
    sequenceIndex: 1,
    phase: "consolidacao_do_jogo_reduzido",
    stageLabel: "direcionamento simples da primeira bola",
    complexityLevel: "moderado",
    alreadyIntroduced: ["receive_direction", "mini_game_2x2_continuity"],
    alreadyPracticedContexts: ["simple_target", "reduced_court"],
    nextStep: ["receive_direction", "set_target_simple"],
    pedagogicalConstraints: [
      "trabalhar primeira bola para alvo ou colega",
      "manter mini 2x2 como referência do mês",
      "usar feedback curto de direção",
    ],
    blockRecommendations: {
      warmup: playfulWarmup(["receive_direction"], ["simple_target", "pair_work"]),
      main: guidedMain(["receive_direction", "set_target_simple"], ["simple_target", "continuity_game"], "desafio_curto", "dupla", "moderada"),
      cooldown: closingBlock([], []),
    },
    source: {
      methodology: "rede_esperanca",
      sourceLabel: "Rede Esperança — abril",
      sourceRef: "direcionamento simples da primeira bola",
    },
  }),
  make08to10Stage({
    id: "08-10_apr_02",
    monthIndex: 4,
    sequenceIndex: 2,
    phase: "consolidacao_do_jogo_reduzido",
    stageLabel: "continuidade com colega certo",
    complexityLevel: "moderado",
    alreadyIntroduced: ["receive_direction", "set_target_simple"],
    alreadyPracticedContexts: ["continuity_game", "pair_work"],
    nextStep: ["two_action_continuity", "mini_game_2x2_continuity"],
    pedagogicalConstraints: [
      "estimular bola no colega certo",
      "usar metas curtas de trocas seguidas",
      "não exigir tomada de decisão abstrata",
    ],
    blockRecommendations: {
      warmup: playfulWarmup(["set_target_simple"], ["pair_work", "simple_target"]),
      main: guidedMain(["two_action_continuity", "mini_game_2x2_continuity"], ["continuity_game", "reduced_court"], "mini_jogo", "equipes_reduzidas", "moderada"),
      cooldown: closingBlock([], []),
    },
    source: {
      methodology: "instituto_compartilhar",
      sourceLabel: "Mini 2x2 — Compartilhar",
      sourceRef: "colega certo e maior estabilidade da continuidade",
    },
  }),
  make08to10Stage({
    id: "08-10_apr_03",
    monthIndex: 4,
    sequenceIndex: 3,
    phase: "consolidacao_do_jogo_reduzido",
    stageLabel: "mini jogo 2x2 com mais estabilidade",
    complexityLevel: "moderado",
    alreadyIntroduced: ["two_action_continuity", "mini_game_2x2_continuity"],
    alreadyPracticedContexts: ["application_game", "reduced_court"],
    nextStep: ["mini_game_2x2_continuity", "receive_direction"],
    pedagogicalConstraints: [
      "valorizar estabilidade da troca",
      "usar regras simples de manutenção do rally",
      "evitar aumento precoce de complexidade",
    ],
    blockRecommendations: {
      warmup: playfulWarmup(["receive_direction", "set_with_movement"], ["pair_work"]),
      main: guidedMain(["mini_game_2x2_continuity", "receive_direction"], ["application_game", "reduced_court"], "mini_jogo", "equipes_reduzidas", "moderada"),
      cooldown: closingBlock([], []),
    },
    source: {
      methodology: "rede_esperanca",
      sourceLabel: "Rede Esperança — abril",
      sourceRef: "consolidação do mini 2x2 com estabilidade",
    },
  }),
  make08to10Stage({
    id: "08-10_may_01",
    monthIndex: 5,
    sequenceIndex: 1,
    phase: "ampliacao_de_repertorio",
    stageLabel: "alternância entre toque e recepção",
    complexityLevel: "moderado",
    alreadyIntroduced: ["receive_direction", "set_with_movement"],
    alreadyPracticedContexts: ["pair_work", "continuity_game"],
    nextStep: ["set_continuity", "two_action_continuity"],
    pedagogicalConstraints: [
      "alternar funções sem pressa",
      "manter foco em controle e continuidade",
      "usar trios quando necessário",
    ],
    blockRecommendations: {
      warmup: playfulWarmup(["set_with_movement", "receive_direction"], ["pair_work", "continuity_game"]),
      main: guidedMain(["set_continuity", "two_action_continuity"], ["continuity_game", "reduced_court"], "estacao", "trio", "moderada"),
      cooldown: closingBlock([], []),
    },
    source: {
      methodology: "rede_esperanca",
      sourceLabel: "Rede Esperança — maio",
      sourceRef: "alternância entre toque e recepção",
    },
  }),
  make08to10Stage({
    id: "08-10_may_02",
    monthIndex: 5,
    sequenceIndex: 2,
    phase: "ampliacao_de_repertorio",
    stageLabel: "leitura simples do espaço livre",
    complexityLevel: "moderado",
    alreadyIntroduced: ["set_continuity", "two_action_continuity"],
    alreadyPracticedContexts: ["application_game", "reduced_court"],
    nextStep: ["mini_game_2x2_continuity", "receive_direction"],
    pedagogicalConstraints: [
      "falar em espaço livre e lado vazio",
      "não usar linguagem tática pesada",
      "aplicar em jogo reduzido",
    ],
    blockRecommendations: {
      warmup: playfulWarmup(["receive_direction"], ["simple_target", "pair_work"]),
      main: guidedMain(["mini_game_2x2_continuity", "receive_direction"], ["application_game", "reduced_court"], "mini_jogo", "equipes_reduzidas", "moderada"),
      cooldown: closingBlock([], []),
    },
    source: {
      methodology: "instituto_compartilhar",
      sourceLabel: "Mini 2x2 — Compartilhar",
      sourceRef: "espaço livre e jogo adaptado",
    },
  }),
  make08to10Stage({
    id: "08-10_may_03",
    monthIndex: 5,
    sequenceIndex: 3,
    phase: "ampliacao_de_repertorio",
    stageLabel: "mini 2x2 com repertório mais variado",
    complexityLevel: "moderado",
    alreadyIntroduced: ["set_continuity", "mini_game_2x2_continuity"],
    alreadyPracticedContexts: ["application_game", "continuity_game"],
    nextStep: ["three_action_continuity", "mini_game_2x2_continuity"],
    pedagogicalConstraints: [
      "manter jogo adaptado",
      "permitir ajuda do colega",
      "não subir complexidade cedo demais",
    ],
    blockRecommendations: {
      warmup: playfulWarmup(["set_continuity", "receive_direction"], ["pair_work"]),
      main: guidedMain(["three_action_continuity", "mini_game_2x2_continuity"], ["application_game", "reduced_court"], "mini_jogo", "equipes_reduzidas", "moderada"),
      cooldown: closingBlock([], []),
    },
    source: {
      methodology: "rede_esperanca",
      sourceLabel: "Rede Esperança — maio",
      sourceRef: "ampliação de repertório com jogo reduzido",
    },
  }),
  make08to10Stage({
    id: "08-10_jun_01",
    monthIndex: 6,
    sequenceIndex: 1,
    phase: "consolidacao_com_autonomia_inicial",
    stageLabel: "jogo reduzido com metas curtas",
    complexityLevel: "moderado",
    alreadyIntroduced: ["mini_game_2x2_continuity", "three_action_continuity"],
    alreadyPracticedContexts: ["application_game", "reduced_court"],
    nextStep: ["mini_game_2x2_continuity", "set_continuity"],
    pedagogicalConstraints: [
      "usar metas curtas por rodada",
      "não subir complexidade sem estabilidade",
      "estimular mais autonomia do grupo",
    ],
    blockRecommendations: {
      warmup: playfulWarmup(["set_continuity"], ["pair_work", "continuity_game"]),
      main: guidedMain(["mini_game_2x2_continuity", "set_continuity"], ["application_game", "reduced_court"], "mini_jogo", "equipes_reduzidas", "moderada"),
      cooldown: closingBlock([], []),
    },
    source: {
      methodology: "rede_esperanca",
      sourceLabel: "Rede Esperança — junho",
      sourceRef: "consolidação com metas curtas",
    },
  }),
  make08to10Stage({
    id: "08-10_jun_02",
    monthIndex: 6,
    sequenceIndex: 2,
    phase: "consolidacao_com_autonomia_inicial",
    stageLabel: "grupo com mais autonomia no mini 2x2",
    complexityLevel: "moderado",
    alreadyIntroduced: ["mini_game_2x2_continuity", "set_continuity"],
    alreadyPracticedContexts: ["application_game", "adapted_rules"],
    nextStep: ["receive_direction", "mini_game_2x2_continuity"],
    pedagogicalConstraints: [
      "deixar o grupo resolver tarefas simples",
      "intervir com poucas regras por vez",
      "manter foco em continuidade",
    ],
    blockRecommendations: {
      warmup: playfulWarmup(["receive_direction", "set_continuity"], ["pair_work"]),
      main: guidedMain(["receive_direction", "mini_game_2x2_continuity"], ["application_game", "adapted_rules"], "mini_jogo", "equipes_reduzidas", "moderada"),
      cooldown: closingBlock([], []),
    },
    source: {
      methodology: "instituto_compartilhar",
      sourceLabel: "Mini 2x2 — Compartilhar",
      sourceRef: "autonomia inicial do grupo sem salto de complexidade",
    },
  }),
  make08to10Stage({
    id: "08-10_jun_03",
    monthIndex: 6,
    sequenceIndex: 3,
    phase: "consolidacao_com_autonomia_inicial",
    stageLabel: "estabilidade do jogo reduzido antes da revisão",
    complexityLevel: "moderado",
    alreadyIntroduced: ["receive_direction", "mini_game_2x2_continuity"],
    alreadyPracticedContexts: ["application_game", "continuity_game"],
    nextStep: ["set_continuity", "three_action_continuity"],
    pedagogicalConstraints: [
      "consolidar antes de aumentar",
      "manter mini 2x2 como jogo central",
      "usar repetição com desafio curto",
    ],
    blockRecommendations: {
      warmup: playfulWarmup(["set_continuity"], ["pair_work"]),
      main: guidedMain(["set_continuity", "three_action_continuity"], ["continuity_game", "reduced_court"], "desafio_curto", "equipes_reduzidas", "moderada"),
      cooldown: closingBlock([], []),
    },
    source: {
      methodology: "rede_esperanca",
      sourceLabel: "Rede Esperança — junho",
      sourceRef: "estabilidade antes da retomada de julho",
    },
  }),
  make08to10Stage({
    id: "08-10_jul_01",
    monthIndex: 7,
    sequenceIndex: 1,
    phase: "retomada_e_revisao",
    stageLabel: "retomada dos fundamentos mais frágeis",
    complexityLevel: "baixo_moderado",
    alreadyIntroduced: ["set_self_control", "receive_simple", "underhand_serve_target"],
    alreadyPracticedContexts: ["pair_work", "simple_target"],
    nextStep: ["receive_simple", "set_target_simple"],
    pedagogicalConstraints: [
      "revisar sem pressa",
      "reforçar os fundamentos mais frágeis",
      "usar tarefas familiares",
    ],
    blockRecommendations: {
      warmup: playfulWarmup(["set_self_control", "receive_simple"], ["pair_work", "simple_target"]),
      main: guidedMain(["receive_simple", "set_target_simple"], ["simple_target", "continuity_game"], "estacao", "dupla", "leve"),
      cooldown: closingBlock([], []),
    },
    source: {
      methodology: "rede_esperanca",
      sourceLabel: "Rede Esperança — julho",
      sourceRef: "retomada e revisão",
    },
  }),
  make08to10Stage({
    id: "08-10_jul_02",
    monthIndex: 7,
    sequenceIndex: 2,
    phase: "retomada_e_revisao",
    stageLabel: "reforço de saque, recepção e toque",
    complexityLevel: "baixo_moderado",
    alreadyIntroduced: ["underhand_serve_target", "receive_simple", "set_target_simple"],
    alreadyPracticedContexts: ["pair_work", "simple_target", "adapted_rules"],
    nextStep: ["two_action_continuity", "mini_game_2x2_intro"],
    pedagogicalConstraints: [
      "reapresentar a estrutura do 2x2 com simplicidade",
      "valorizar acerto técnico básico",
      "evitar sobrecarga de comandos",
    ],
    blockRecommendations: {
      warmup: playfulWarmup(["underhand_serve_target", "set_target_simple"], ["simple_target"]),
      main: guidedMain(["two_action_continuity", "mini_game_2x2_intro"], ["continuity_game", "reduced_court"], "desafio_curto", "trio", "leve"),
      cooldown: closingBlock([], []),
    },
    source: {
      methodology: "instituto_compartilhar",
      sourceLabel: "Mini 2x2 — Compartilhar",
      sourceRef: "retomada progressiva após pausa",
    },
  }),
  make08to10Stage({
    id: "08-10_jul_03",
    monthIndex: 7,
    sequenceIndex: 3,
    phase: "retomada_e_revisao",
    stageLabel: "mini 2x2 retomado com segurança",
    complexityLevel: "baixo_moderado",
    alreadyIntroduced: ["two_action_continuity", "mini_game_2x2_intro"],
    alreadyPracticedContexts: ["reduced_court", "adapted_rules"],
    nextStep: ["mini_game_2x2_continuity", "receive_direction"],
    pedagogicalConstraints: [
      "retomar confiança da turma",
      "deixar o jogo curto e acessível",
      "evitar exigência alta logo na volta",
    ],
    blockRecommendations: {
      warmup: playfulWarmup(["receive_simple", "set_target_simple"], ["pair_work"]),
      main: guidedMain(["mini_game_2x2_continuity", "receive_direction"], ["reduced_court", "application_game"], "mini_jogo", "equipes_reduzidas", "leve"),
      cooldown: closingBlock([], []),
    },
    source: {
      methodology: "rede_esperanca",
      sourceLabel: "Rede Esperança — julho",
      sourceRef: "retomada do jogo reduzido com segurança",
    },
  }),
  make08to10Stage({
    id: "08-10_aug_01",
    monthIndex: 8,
    sequenceIndex: 1,
    phase: "integracao_progressiva",
    stageLabel: "integração mais consistente entre recepção e envio",
    complexityLevel: "moderado",
    alreadyIntroduced: ["mini_game_2x2_continuity", "receive_direction"],
    alreadyPracticedContexts: ["continuity_game", "application_game"],
    nextStep: ["set_continuity", "two_action_continuity"],
    pedagogicalConstraints: [
      "pedir maior fluidez sem pular etapas",
      "usar tarefas com repetição orientada",
      "manter foco na continuidade",
    ],
    blockRecommendations: {
      warmup: playfulWarmup(["receive_direction", "set_continuity"], ["pair_work", "continuity_game"]),
      main: guidedMain(["set_continuity", "two_action_continuity"], ["continuity_game", "reduced_court"], "estacao", "trio", "moderada"),
      cooldown: closingBlock([], []),
    },
    source: {
      methodology: "rede_esperanca",
      sourceLabel: "Rede Esperança — agosto",
      sourceRef: "integração dos fundamentos com mais constância",
    },
  }),
  make08to10Stage({
    id: "08-10_aug_02",
    monthIndex: 8,
    sequenceIndex: 2,
    phase: "integracao_progressiva",
    stageLabel: "continuidade mais estável em mini 2x2",
    complexityLevel: "moderado",
    alreadyIntroduced: ["set_continuity", "two_action_continuity"],
    alreadyPracticedContexts: ["continuity_game", "reduced_court"],
    nextStep: ["mini_game_2x2_continuity", "three_action_continuity"],
    pedagogicalConstraints: [
      "pedir mais estabilidade antes de ampliar",
      "usar quadra reduzida e metas curtas",
      "valorizar sequência com ajuda do colega",
    ],
    blockRecommendations: {
      warmup: playfulWarmup(["set_continuity"], ["pair_work", "continuity_game"]),
      main: guidedMain(["mini_game_2x2_continuity", "three_action_continuity"], ["application_game", "reduced_court"], "mini_jogo", "equipes_reduzidas", "moderada"),
      cooldown: closingBlock([], []),
    },
    source: {
      methodology: "instituto_compartilhar",
      sourceLabel: "Mini 2x2 — Compartilhar",
      sourceRef: "mini 2x2 mais fluido e estável",
    },
  }),
  make08to10Stage({
    id: "08-10_aug_03",
    monthIndex: 8,
    sequenceIndex: 3,
    phase: "integracao_progressiva",
    stageLabel: "mini jogo mais fluido e autônomo",
    complexityLevel: "moderado",
    alreadyIntroduced: ["mini_game_2x2_continuity", "three_action_continuity"],
    alreadyPracticedContexts: ["application_game", "adapted_rules"],
    nextStep: ["mini_game_2x2_continuity", "receive_direction"],
    pedagogicalConstraints: [
      "ganhar fluidez sem virar jogo formal",
      "usar decisões simples de espaço e colega",
      "manter professor como apoio e não condutor total",
    ],
    blockRecommendations: {
      warmup: playfulWarmup(["receive_direction", "set_continuity"], ["pair_work"]),
      main: guidedMain(["mini_game_2x2_continuity", "receive_direction"], ["application_game", "reduced_court"], "mini_jogo", "equipes_reduzidas", "moderada"),
      cooldown: closingBlock([], []),
    },
    source: {
      methodology: "rede_esperanca",
      sourceLabel: "Rede Esperança — agosto",
      sourceRef: "jogo mais fluido antes da aplicação de setembro",
    },
  }),
  make08to10Stage({
    id: "08-10_sep_01",
    monthIndex: 9,
    sequenceIndex: 1,
    phase: "aplicacao_ludica",
    stageLabel: "jogos de aplicação com transições simples",
    complexityLevel: "moderado",
    alreadyIntroduced: ["mini_game_2x2_continuity", "receive_direction"],
    alreadyPracticedContexts: ["application_game", "reduced_court"],
    nextStep: ["three_action_continuity", "coverage_intro"],
    pedagogicalConstraints: [
      "usar aplicação em jogo como centro do mês",
      "falar em cobertura de forma básica e concreta",
      "não antecipar leitura tática pesada",
    ],
    blockRecommendations: {
      warmup: playfulWarmup(["receive_direction", "set_continuity"], ["pair_work", "application_game"]),
      main: guidedMain(["three_action_continuity", "coverage_intro"], ["application_game", "reduced_court"], "mini_jogo", "equipes_reduzidas", "moderada"),
      cooldown: closingBlock([], []),
    },
    source: {
      methodology: "rede_esperanca",
      sourceLabel: "Rede Esperança — setembro",
      sourceRef: "transições simples e cobertura inicial",
    },
  }),
  make08to10Stage({
    id: "08-10_sep_02",
    monthIndex: 9,
    sequenceIndex: 2,
    phase: "aplicacao_ludica",
    stageLabel: "cobertura inicial muito básica",
    complexityLevel: "moderado",
    alreadyIntroduced: ["three_action_continuity", "coverage_intro"],
    alreadyPracticedContexts: ["application_game", "continuity_game"],
    nextStep: ["mini_game_2x2_continuity", "coverage_intro"],
    pedagogicalConstraints: [
      "tratar cobertura como ajuda ao colega",
      "usar deslocamentos curtos e claros",
      "manter jogo reduzido",
    ],
    blockRecommendations: {
      warmup: playfulWarmup(["set_with_movement"], ["pair_work"]),
      main: guidedMain(["coverage_intro", "mini_game_2x2_continuity"], ["application_game", "reduced_court"], "mini_jogo", "equipes_reduzidas", "moderada"),
      cooldown: closingBlock([], []),
    },
    source: {
      methodology: "instituto_compartilhar",
      sourceLabel: "Mini 2x2 — Compartilhar",
      sourceRef: "cobertura como ajuda básica ao colega",
    },
  }),
  make08to10Stage({
    id: "08-10_sep_03",
    monthIndex: 9,
    sequenceIndex: 3,
    phase: "aplicacao_ludica",
    stageLabel: "mini 2x2 aplicado com mais continuidade",
    complexityLevel: "moderado",
    alreadyIntroduced: ["coverage_intro", "mini_game_2x2_continuity"],
    alreadyPracticedContexts: ["application_game", "reduced_court"],
    nextStep: ["three_action_continuity", "mini_game_2x2_continuity"],
    pedagogicalConstraints: [
      "consolidar aplicação lúdica",
      "usar desafios combinados curtos",
      "evitar complexidade adulta",
    ],
    blockRecommendations: {
      warmup: playfulWarmup(["receive_direction", "coverage_intro"], ["pair_work"]),
      main: guidedMain(["three_action_continuity", "mini_game_2x2_continuity"], ["application_game", "reduced_court"], "mini_jogo", "equipes_reduzidas", "moderada"),
      cooldown: closingBlock([], []),
    },
    source: {
      methodology: "rede_esperanca",
      sourceLabel: "Rede Esperança — setembro",
      sourceRef: "aplicação do jogo reduzido com continuidade",
    },
  }),
  make08to10Stage({
    id: "08-10_oct_01",
    monthIndex: 10,
    sequenceIndex: 1,
    phase: "consolidacao_da_decisao_simples",
    stageLabel: "consolidação do jogo com 2 a 3 ações",
    complexityLevel: "moderado",
    alreadyIntroduced: ["three_action_continuity", "mini_game_2x2_continuity"],
    alreadyPracticedContexts: ["continuity_game", "application_game"],
    nextStep: ["three_action_continuity", "receive_direction"],
    pedagogicalConstraints: [
      "manter foco em continuidade",
      "evitar abstração tática pesada",
      "usar decisões simples e concretas",
    ],
    blockRecommendations: {
      warmup: playfulWarmup(["set_continuity", "receive_direction"], ["pair_work"]),
      main: guidedMain(["three_action_continuity", "receive_direction"], ["continuity_game", "application_game"], "mini_jogo", "equipes_reduzidas", "moderada"),
      cooldown: closingBlock([], []),
    },
    source: {
      methodology: "rede_esperanca",
      sourceLabel: "Rede Esperança — outubro",
      sourceRef: "consolidação das 2 a 3 ações",
    },
  }),
  make08to10Stage({
    id: "08-10_oct_02",
    monthIndex: 10,
    sequenceIndex: 2,
    phase: "consolidacao_da_decisao_simples",
    stageLabel: "tomada de decisão simples no espaço livre",
    complexityLevel: "moderado",
    alreadyIntroduced: ["receive_direction", "mini_game_2x2_continuity"],
    alreadyPracticedContexts: ["application_game", "reduced_court"],
    nextStep: ["mini_game_2x2_continuity", "coverage_intro"],
    pedagogicalConstraints: [
      "usar perguntas concretas como lado vazio e colega livre",
      "não usar leitura tática abstrata",
      "aplicar em mini jogo",
    ],
    blockRecommendations: {
      warmup: playfulWarmup(["receive_direction"], ["simple_target", "pair_work"]),
      main: guidedMain(["mini_game_2x2_continuity", "coverage_intro"], ["application_game", "reduced_court"], "mini_jogo", "equipes_reduzidas", "moderada"),
      cooldown: closingBlock([], []),
    },
    source: {
      methodology: "instituto_compartilhar",
      sourceLabel: "Mini 2x2 — Compartilhar",
      sourceRef: "decisão simples sem abstração tática pesada",
    },
  }),
  make08to10Stage({
    id: "08-10_oct_03",
    monthIndex: 10,
    sequenceIndex: 3,
    phase: "consolidacao_da_decisao_simples",
    stageLabel: "mini jogo estável com desafios combinados",
    complexityLevel: "moderado",
    alreadyIntroduced: ["mini_game_2x2_continuity", "coverage_intro"],
    alreadyPracticedContexts: ["application_game", "adapted_rules"],
    nextStep: ["three_action_continuity", "mini_game_2x2_continuity"],
    pedagogicalConstraints: [
      "usar combinações curtas de desafio",
      "manter jogo adaptado e claro",
      "evitar regras demais ao mesmo tempo",
    ],
    blockRecommendations: {
      warmup: playfulWarmup(["set_continuity"], ["pair_work"]),
      main: guidedMain(["three_action_continuity", "mini_game_2x2_continuity"], ["application_game", "adapted_rules"], "mini_jogo", "equipes_reduzidas", "moderada"),
      cooldown: closingBlock([], []),
    },
    source: {
      methodology: "rede_esperanca",
      sourceLabel: "Rede Esperança — outubro",
      sourceRef: "desafios combinados e jogo estável",
    },
  }),
  make08to10Stage({
    id: "08-10_nov_01",
    monthIndex: 11,
    sequenceIndex: 1,
    phase: "aplicacao_autonoma",
    stageLabel: "aplicação lúdica com maior autonomia",
    complexityLevel: "moderado",
    alreadyIntroduced: ["mini_game_2x2_continuity", "three_action_continuity"],
    alreadyPracticedContexts: ["application_game", "adapted_rules"],
    nextStep: ["mini_game_2x2_continuity", "receive_direction"],
    pedagogicalConstraints: [
      "deixar a turma resolver mais situações simples",
      "manter ludicidade até o fim do ciclo",
      "usar intervenção curta do professor",
    ],
    blockRecommendations: {
      warmup: playfulWarmup(["receive_direction", "set_continuity"], ["pair_work"]),
      main: guidedMain(["mini_game_2x2_continuity", "receive_direction"], ["application_game", "adapted_rules"], "mini_jogo", "equipes_reduzidas", "moderada"),
      cooldown: closingBlock([], []),
    },
    source: {
      methodology: "rede_esperanca",
      sourceLabel: "Rede Esperança — novembro",
      sourceRef: "aplicação lúdica e autonomia",
    },
  }),
  make08to10Stage({
    id: "08-10_nov_02",
    monthIndex: 11,
    sequenceIndex: 2,
    phase: "aplicacao_autonoma",
    stageLabel: "desafios combinados em mini jogo",
    complexityLevel: "moderado",
    alreadyIntroduced: ["mini_game_2x2_continuity", "coverage_intro"],
    alreadyPracticedContexts: ["application_game", "reduced_court"],
    nextStep: ["three_action_continuity", "coverage_intro"],
    pedagogicalConstraints: [
      "combinar dois desafios por rodada no máximo",
      "manter foco em jogo reduzido",
      "não endurecer linguagem",
    ],
    blockRecommendations: {
      warmup: playfulWarmup(["coverage_intro"], ["pair_work"]),
      main: guidedMain(["three_action_continuity", "coverage_intro"], ["application_game", "reduced_court"], "mini_jogo", "equipes_reduzidas", "moderada"),
      cooldown: closingBlock([], []),
    },
    source: {
      methodology: "instituto_compartilhar",
      sourceLabel: "Mini 2x2 — Compartilhar",
      sourceRef: "desafios combinados e jogo mais autônomo",
    },
  }),
  make08to10Stage({
    id: "08-10_nov_03",
    monthIndex: 11,
    sequenceIndex: 3,
    phase: "aplicacao_autonoma",
    stageLabel: "jogo autônomo com apoio pontual do professor",
    complexityLevel: "moderado",
    alreadyIntroduced: ["three_action_continuity", "mini_game_2x2_continuity"],
    alreadyPracticedContexts: ["application_game", "adapted_rules"],
    nextStep: ["mini_game_2x2_continuity", "set_continuity"],
    pedagogicalConstraints: [
      "professor atua mais como ajuste pontual",
      "preservar identidade da categoria",
      "não aproximar demais do 6x6",
    ],
    blockRecommendations: {
      warmup: playfulWarmup(["set_continuity", "receive_direction"], ["pair_work"]),
      main: guidedMain(["mini_game_2x2_continuity", "set_continuity"], ["application_game", "adapted_rules"], "mini_jogo", "equipes_reduzidas", "moderada"),
      cooldown: closingBlock([], []),
    },
    source: {
      methodology: "rede_esperanca",
      sourceLabel: "Rede Esperança — novembro",
      sourceRef: "autonomia do jogo com apoio pontual",
    },
  }),
  make08to10Stage({
    id: "08-10_dec_01",
    monthIndex: 12,
    sequenceIndex: 1,
    phase: "fechamento_e_integracao",
    stageLabel: "revisão integrada dos fundamentos do ano",
    complexityLevel: "baixo_moderado",
    alreadyIntroduced: ["set_self_control", "receive_simple", "mini_game_2x2_continuity"],
    alreadyPracticedContexts: ["pair_work", "application_game"],
    nextStep: ["set_continuity", "receive_direction"],
    pedagogicalConstraints: [
      "usar tom de fechamento e revisão",
      "retomar fundamentos centrais do ano",
      "manter tarefas leves e positivas",
    ],
    blockRecommendations: {
      warmup: playfulWarmup(["set_self_control", "receive_simple"], ["pair_work"]),
      main: guidedMain(["set_continuity", "receive_direction"], ["continuity_game", "simple_target"], "estacao", "trio", "leve"),
      cooldown: closingBlock([], []),
    },
    source: {
      methodology: "rede_esperanca",
      sourceLabel: "Rede Esperança — dezembro",
      sourceRef: "revisão integrada do ciclo anual",
    },
  }),
  make08to10Stage({
    id: "08-10_dec_02",
    monthIndex: 12,
    sequenceIndex: 2,
    phase: "fechamento_e_integracao",
    stageLabel: "jogos integradores com desafios leves",
    complexityLevel: "baixo_moderado",
    alreadyIntroduced: ["mini_game_2x2_continuity", "set_continuity"],
    alreadyPracticedContexts: ["application_game", "adapted_rules"],
    nextStep: ["mini_game_2x2_continuity", "three_action_continuity"],
    pedagogicalConstraints: [
      "usar clima de fechamento do ciclo",
      "trabalhar com desafios leves e lúdicos",
      "valorizar participação da turma",
    ],
    blockRecommendations: {
      warmup: playfulWarmup(["set_continuity"], ["pair_work"]),
      main: guidedMain(["mini_game_2x2_continuity", "three_action_continuity"], ["application_game", "adapted_rules"], "mini_jogo", "equipes_reduzidas", "leve"),
      cooldown: closingBlock([], []),
    },
    source: {
      methodology: "instituto_compartilhar",
      sourceLabel: "Mini 2x2 — Compartilhar",
      sourceRef: "jogos integradores e desafios leves",
    },
  }),
  make08to10Stage({
    id: "08-10_dec_03",
    monthIndex: 12,
    sequenceIndex: 3,
    phase: "fechamento_e_integracao",
    stageLabel: "avaliação pedagógica leve e encerramento",
    complexityLevel: "baixo_moderado",
    alreadyIntroduced: ["mini_game_2x2_continuity", "receive_direction", "set_continuity"],
    alreadyPracticedContexts: ["application_game", "reduced_court"],
    nextStep: ["mini_game_2x2_continuity"],
    pedagogicalConstraints: [
      "usar observação leve e conversa curta",
      "fechar o ano com jogo integrado",
      "não aumentar complexidade no encerramento",
    ],
    blockRecommendations: {
      warmup: playfulWarmup(["receive_direction"], ["pair_work"]),
      main: guidedMain(["mini_game_2x2_continuity"], ["application_game", "reduced_court"], "mini_jogo", "equipes_reduzidas", "leve"),
      cooldown: closingBlock([], []),
    },
    source: {
      methodology: "rede_esperanca",
      sourceLabel: "Rede Esperança — dezembro",
      sourceRef: "encerramento e avaliação pedagógica leve",
    },
  }),
];

const STAGES_11_TO_12: PedagogicalProgressionStage[] = [
  make11to12Stage({
    id: "11-12_jan_01",
    monthIndex: 1,
    sequenceIndex: 1,
    phase: "estruturacao_dos_fundamentos",
    stageLabel: "mini 3x3 inicial com cooperação e organização",
    complexityLevel: "moderado",
    alreadyIntroduced: ["underhand_serve_target", "set_continuity", "mini_game_2x2_continuity"],
    alreadyPracticedContexts: ["trio_work", "continuity_game", "application_game"],
    nextStep: ["mini_game_3x3_intro", "defense_control_intro"],
    pedagogicalConstraints: [
      "aumentar cooperação e organização",
      "não virar jogo formal adulto",
      "usar regras adaptadas e funções simples",
    ],
    blockRecommendations: {
      warmup: playfulWarmup(["set_with_movement", "receive_direction"], ["trio_work", "continuity_game"], "trio"),
      main: guidedMain(["mini_game_3x3_intro", "defense_control_intro"], ["application_game", "reduced_court"], "mini_jogo", "equipes_reduzidas", "moderada"),
      cooldown: closingBlock([], []),
    },
    source: {
      methodology: "instituto_compartilhar",
      sourceLabel: "Mini 3x3 — janeiro",
      sourceRef: "entrada no mini 3x3 com defesa inicial e mais cooperação",
    },
  }),
  make11to12Stage({
    id: "11-12_feb_01",
    monthIndex: 2,
    sequenceIndex: 1,
    phase: "estruturacao_dos_fundamentos",
    stageLabel: "manchete inicial com organização do trio",
    complexityLevel: "moderado",
    alreadyIntroduced: ["mini_game_3x3_intro", "defense_control_intro"],
    alreadyPracticedContexts: ["trio_work", "simple_target", "continuity_game"],
    nextStep: ["receive_direction", "mini_game_3x3_intro"],
    pedagogicalConstraints: [
      "organizar a primeira bola no trio",
      "manter mini 3x3 como jogo base",
      "evitar formalismo de sistema adulto",
    ],
    blockRecommendations: {
      warmup: playfulWarmup(["receive_direction"], ["trio_work", "simple_target"], "trio"),
      main: guidedMain(["receive_direction", "mini_game_3x3_intro"], ["continuity_game", "reduced_court"], "estacao", "trio", "moderada"),
      cooldown: closingBlock([], []),
    },
    source: {
      methodology: "instituto_compartilhar",
      sourceLabel: "Mini 3x3 — fevereiro",
      sourceRef: "manchete inicial e organização do trio",
    },
  }),
  make11to12Stage({
    id: "11-12_mar_01",
    monthIndex: 3,
    sequenceIndex: 1,
    phase: "evolucao_tecnica_e_organizacao",
    stageLabel: "defesa inicial e cobertura básica no mini 3x3",
    complexityLevel: "moderado",
    alreadyIntroduced: ["receive_direction", "mini_game_3x3_intro"],
    alreadyPracticedContexts: ["trio_work", "continuity_game", "application_game"],
    nextStep: ["defense_control_intro", "coverage_intro"],
    pedagogicalConstraints: [
      "tratar cobertura como ajuda ao colega",
      "manter jogo reduzido e decisões claras",
      "não transformar em sistema tático completo",
    ],
    blockRecommendations: {
      warmup: playfulWarmup(["receive_direction", "defense_control_intro"], ["trio_work", "continuity_game"], "trio"),
      main: guidedMain(["defense_control_intro", "coverage_intro"], ["application_game", "reduced_court"], "mini_jogo", "equipes_reduzidas", "moderada"),
      cooldown: closingBlock([], []),
    },
    source: {
      methodology: "instituto_compartilhar",
      sourceLabel: "Mini 3x3 — março",
      sourceRef: "defesa e cobertura básica com cooperação",
    },
  }),
  make11to12Stage({
    id: "11-12_apr_01",
    monthIndex: 4,
    sequenceIndex: 1,
    phase: "evolucao_tecnica_e_organizacao",
    stageLabel: "ataque inicial com bola organizada pelo trio",
    complexityLevel: "moderado",
    alreadyIntroduced: ["defense_control_intro", "coverage_intro"],
    alreadyPracticedContexts: ["trio_work", "application_game"],
    nextStep: ["attack_arm_intro", "mini_game_3x3_intro"],
    pedagogicalConstraints: [
      "ataque inicial sem cobrança de potência adulta",
      "usar organização simples do trio",
      "manter jogo reduzido como contexto",
    ],
    blockRecommendations: {
      warmup: playfulWarmup(["set_continuity", "receive_direction"], ["trio_work", "simple_target"], "trio"),
      main: guidedMain(["attack_arm_intro", "mini_game_3x3_intro"], ["application_game", "reduced_court"], "estacao", "trio", "moderada"),
      cooldown: closingBlock([], []),
    },
    source: {
      methodology: "instituto_compartilhar",
      sourceLabel: "Mini 3x3 — abril",
      sourceRef: "ataque inicial com organização do trio",
    },
  }),
  make11to12Stage({
    id: "11-12_may_01",
    monthIndex: 5,
    sequenceIndex: 1,
    phase: "evolucao_tecnica_e_organizacao",
    stageLabel: "bloqueio inicial e cobertura mais funcional",
    complexityLevel: "moderado",
    alreadyIntroduced: ["attack_arm_intro", "coverage_intro"],
    alreadyPracticedContexts: ["application_game", "reduced_court"],
    nextStep: ["block_marking_intro", "coverage_intro"],
    pedagogicalConstraints: [
      "tratar bloqueio como marcação inicial",
      "não cobrar tempo de bloqueio adulto",
      "manter cooperação do trio",
    ],
    blockRecommendations: {
      warmup: playfulWarmup(["coverage_intro"], ["trio_work", "continuity_game"], "trio"),
      main: guidedMain(["block_marking_intro", "coverage_intro"], ["application_game", "reduced_court"], "desafio_curto", "trio", "moderada"),
      cooldown: closingBlock([], []),
    },
    source: {
      methodology: "instituto_compartilhar",
      sourceLabel: "Mini 3x3 — maio",
      sourceRef: "bloqueio inicial e cobertura funcional",
    },
  }),
  make11to12Stage({
    id: "11-12_jun_01",
    monthIndex: 6,
    sequenceIndex: 1,
    phase: "mini_3x3_com_mais_continuidade",
    stageLabel: "mini 3x3 com mais continuidade e transição simples",
    complexityLevel: "moderado",
    alreadyIntroduced: ["block_marking_intro", "coverage_intro"],
    alreadyPracticedContexts: ["application_game", "reduced_court", "continuity_game"],
    nextStep: ["three_action_continuity", "mini_game_3x3_intro"],
    pedagogicalConstraints: [
      "pedir mais continuidade sem acelerar demais",
      "usar transição simples entre defender e devolver",
      "não virar sistema adulto",
    ],
    blockRecommendations: {
      warmup: playfulWarmup(["receive_direction", "set_continuity"], ["trio_work", "continuity_game"], "trio"),
      main: guidedMain(["three_action_continuity", "mini_game_3x3_intro"], ["application_game", "reduced_court"], "mini_jogo", "equipes_reduzidas", "moderada"),
      cooldown: closingBlock([], []),
    },
    source: {
      methodology: "instituto_compartilhar",
      sourceLabel: "Mini 3x3 — junho",
      sourceRef: "mais continuidade e transição simples",
    },
  }),
  make11to12Stage({
    id: "11-12_jul_01",
    monthIndex: 7,
    sequenceIndex: 1,
    phase: "retomada_e_revisao",
    stageLabel: "retomada de fundamentos e organização do mini 3x3",
    complexityLevel: "moderado",
    alreadyIntroduced: ["mini_game_3x3_intro", "defense_control_intro", "coverage_intro"],
    alreadyPracticedContexts: ["trio_work", "application_game"],
    nextStep: ["receive_direction", "defense_control_intro"],
    pedagogicalConstraints: [
      "revisar sem voltar para uma linguagem infantilizada",
      "retomar organização do trio",
      "usar tarefas conhecidas com um novo detalhe",
    ],
    blockRecommendations: {
      warmup: playfulWarmup(["receive_direction", "set_continuity"], ["trio_work", "simple_target"], "trio"),
      main: guidedMain(["receive_direction", "defense_control_intro"], ["continuity_game", "reduced_court"], "estacao", "trio", "moderada"),
      cooldown: closingBlock([], []),
    },
    source: {
      methodology: "instituto_compartilhar",
      sourceLabel: "Mini 3x3 — julho",
      sourceRef: "retomada com identidade da categoria",
    },
  }),
  make11to12Stage({
    id: "11-12_aug_01",
    monthIndex: 8,
    sequenceIndex: 1,
    phase: "mini_3x3_com_mais_continuidade",
    stageLabel: "mini 3x3 mais fluido com organização ofensiva simples",
    complexityLevel: "moderado",
    alreadyIntroduced: ["attack_arm_intro", "three_action_continuity"],
    alreadyPracticedContexts: ["application_game", "reduced_court"],
    nextStep: ["attack_arm_intro", "coverage_intro"],
    pedagogicalConstraints: [
      "organizar ataque inicial sem formalismo adulto",
      "manter cooperação e cobertura simples",
      "dar progressão em mini jogo",
    ],
    blockRecommendations: {
      warmup: playfulWarmup(["set_continuity", "attack_arm_intro"], ["trio_work", "continuity_game"], "trio"),
      main: guidedMain(["attack_arm_intro", "coverage_intro"], ["application_game", "reduced_court"], "mini_jogo", "equipes_reduzidas", "moderada"),
      cooldown: closingBlock([], []),
    },
    source: {
      methodology: "instituto_compartilhar",
      sourceLabel: "Mini 3x3 — agosto",
      sourceRef: "mini 3x3 mais fluido e ofensivo",
    },
  }),
  make11to12Stage({
    id: "11-12_sep_01",
    monthIndex: 9,
    sequenceIndex: 1,
    phase: "aplicacao_e_consolidacao",
    stageLabel: "aplicação do mini 3x3 com defesa, cobertura e ataque inicial",
    complexityLevel: "moderado",
    alreadyIntroduced: ["defense_control_intro", "coverage_intro", "attack_arm_intro"],
    alreadyPracticedContexts: ["application_game", "reduced_court", "continuity_game"],
    nextStep: ["mini_game_3x3_intro", "block_marking_intro"],
    pedagogicalConstraints: [
      "integrar fundamentos em situação de jogo",
      "manter 3x3 como referência da categoria",
      "evitar cara de treino adulto",
    ],
    blockRecommendations: {
      warmup: playfulWarmup(["defense_control_intro", "coverage_intro"], ["trio_work", "continuity_game"], "trio"),
      main: guidedMain(["mini_game_3x3_intro", "block_marking_intro"], ["application_game", "reduced_court"], "mini_jogo", "equipes_reduzidas", "moderada"),
      cooldown: closingBlock([], []),
    },
    source: {
      methodology: "instituto_compartilhar",
      sourceLabel: "Mini 3x3 — setembro",
      sourceRef: "aplicação integrada do mini 3x3",
    },
  }),
  make11to12Stage({
    id: "11-12_oct_01",
    monthIndex: 10,
    sequenceIndex: 1,
    phase: "aplicacao_e_consolidacao",
    stageLabel: "consolidação com mais leitura funcional do jogo",
    complexityLevel: "moderado",
    alreadyIntroduced: ["block_marking_intro", "coverage_intro", "mini_game_3x3_intro"],
    alreadyPracticedContexts: ["application_game", "reduced_court"],
    nextStep: ["three_action_continuity", "coverage_intro"],
    pedagogicalConstraints: [
      "falar em organização funcional, não em tática adulta",
      "usar decisões simples de cobertura e ataque",
      "manter mini 3x3 como eixo",
    ],
    blockRecommendations: {
      warmup: playfulWarmup(["receive_direction", "coverage_intro"], ["trio_work"] , "trio"),
      main: guidedMain(["three_action_continuity", "coverage_intro"], ["application_game", "reduced_court"], "mini_jogo", "equipes_reduzidas", "moderada"),
      cooldown: closingBlock([], []),
    },
    source: {
      methodology: "instituto_compartilhar",
      sourceLabel: "Mini 3x3 — outubro",
      sourceRef: "mais leitura funcional sem formalismo adulto",
    },
  }),
  make11to12Stage({
    id: "11-12_nov_01",
    monthIndex: 11,
    sequenceIndex: 1,
    phase: "aplicacao_e_consolidacao",
    stageLabel: "mini 3x3 autônomo com desafios combinados",
    complexityLevel: "moderado",
    alreadyIntroduced: ["mini_game_3x3_intro", "three_action_continuity", "coverage_intro"],
    alreadyPracticedContexts: ["application_game", "adapted_rules"],
    nextStep: ["block_marking_intro", "attack_arm_intro"],
    pedagogicalConstraints: [
      "usar desafios combinados e curtos",
      "manter coerência com a idade",
      "não virar treino tático de adulto",
    ],
    blockRecommendations: {
      warmup: playfulWarmup(["set_continuity", "receive_direction"], ["trio_work"] , "trio"),
      main: guidedMain(["block_marking_intro", "attack_arm_intro"], ["application_game", "adapted_rules"], "mini_jogo", "equipes_reduzidas", "moderada"),
      cooldown: closingBlock([], []),
    },
    source: {
      methodology: "instituto_compartilhar",
      sourceLabel: "Mini 3x3 — novembro",
      sourceRef: "autonomia com desafios combinados e identidade da categoria",
    },
  }),
  make11to12Stage({
    id: "11-12_dec_01",
    monthIndex: 12,
    sequenceIndex: 1,
    phase: "fechamento_e_integracao",
    stageLabel: "fechamento do mini 3x3 com jogos integradores",
    complexityLevel: "moderado",
    alreadyIntroduced: ["defense_control_intro", "coverage_intro", "attack_arm_intro", "block_marking_intro"],
    alreadyPracticedContexts: ["application_game", "adapted_rules", "reduced_court"],
    nextStep: ["mini_game_3x3_intro", "three_action_continuity"],
    pedagogicalConstraints: [
      "fechar o ano com integração dos fundamentos",
      "usar avaliação pedagógica leve",
      "preservar caráter de mini 3x3",
    ],
    blockRecommendations: {
      warmup: playfulWarmup(["receive_direction", "set_continuity"], ["trio_work", "continuity_game"], "trio"),
      main: guidedMain(["mini_game_3x3_intro", "three_action_continuity"], ["application_game", "reduced_court"], "mini_jogo", "equipes_reduzidas", "moderada"),
      cooldown: closingBlock([], []),
    },
    source: {
      methodology: "instituto_compartilhar",
      sourceLabel: "Mini 3x3 — dezembro",
      sourceRef: "jogos integradores e fechamento anual",
    },
  }),
];

const STAGES_13_TO_14: PedagogicalProgressionStage[] = [
  make13to14Stage({
    id: "13-14_jan_01",
    monthIndex: 1,
    sequenceIndex: 1,
    phase: "transicao_para_o_jogo_formal",
    stageLabel: "mini 4x4 como ponte organizada para o jogo formal",
    complexityLevel: "moderado_alto",
    alreadyIntroduced: ["mini_game_3x3_intro", "defense_control_intro", "coverage_intro"],
    alreadyPracticedContexts: ["application_game", "trio_work", "reduced_court"],
    nextStep: ["three_action_continuity", "attack_arm_intro"],
    pedagogicalConstraints: [
      "tratar como transição e não como 6x6 completo",
      "organizar funções simples no 4x4",
      "manter sequência de 3 contatos como eixo",
    ],
    blockRecommendations: {
      warmup: playfulWarmup(["receive_direction", "set_continuity"], ["trio_work", "continuity_game"], "trio"),
      main: guidedMain(["three_action_continuity", "attack_arm_intro"], ["application_game", "reduced_court"], "mini_jogo", "equipes_reduzidas", "moderada_alta"),
      cooldown: closingBlock([], []),
    },
    source: {
      methodology: "instituto_compartilhar",
      sourceLabel: "Mini 4x4 — janeiro",
      sourceRef: "ponte inicial entre mini 3x3 e organização do 4x4",
    },
  }),
  make13to14Stage({
    id: "13-14_feb_01",
    monthIndex: 2,
    sequenceIndex: 1,
    phase: "transicao_para_o_jogo_formal",
    stageLabel: "recepção, levantamento e ataque inicial em mini 4x4",
    complexityLevel: "moderado_alto",
    alreadyIntroduced: ["three_action_continuity", "attack_arm_intro"],
    alreadyPracticedContexts: ["application_game", "reduced_court", "continuity_game"],
    nextStep: ["receive_direction", "attack_arm_intro"],
    pedagogicalConstraints: [
      "organizar a construção com 3 contatos",
      "não antecipar sistema adulto fixo",
      "manter jogo reduzido e leitura funcional",
    ],
    blockRecommendations: {
      warmup: playfulWarmup(["receive_direction", "set_continuity"], ["trio_work", "simple_target"], "trio"),
      main: guidedMain(["receive_direction", "attack_arm_intro"], ["application_game", "reduced_court"], "estacao", "equipes_reduzidas", "moderada_alta"),
      cooldown: closingBlock([], []),
    },
    source: {
      methodology: "instituto_compartilhar",
      sourceLabel: "Mini 4x4 — fevereiro",
      sourceRef: "construção inicial com recepção, levantamento e ataque",
    },
  }),
  make13to14Stage({
    id: "13-14_mar_01",
    monthIndex: 3,
    sequenceIndex: 1,
    phase: "organizacao_funcional_do_jogo",
    stageLabel: "defesa e cobertura funcional no mini 4x4",
    complexityLevel: "moderado_alto",
    alreadyIntroduced: ["attack_arm_intro", "receive_direction"],
    alreadyPracticedContexts: ["application_game", "reduced_court"],
    nextStep: ["defense_control_intro", "coverage_intro"],
    pedagogicalConstraints: [
      "trabalhar cobertura como organização coletiva simples",
      "manter decisões funcionais em vez de tática adulta completa",
      "usar mini 4x4 como contexto principal",
    ],
    blockRecommendations: {
      warmup: playfulWarmup(["defense_control_intro", "coverage_intro"], ["trio_work", "continuity_game"], "trio"),
      main: guidedMain(["defense_control_intro", "coverage_intro"], ["application_game", "reduced_court"], "mini_jogo", "equipes_reduzidas", "moderada_alta"),
      cooldown: closingBlock([], []),
    },
    source: {
      methodology: "instituto_compartilhar",
      sourceLabel: "Mini 4x4 — março",
      sourceRef: "defesa e cobertura funcional no 4x4",
    },
  }),
  make13to14Stage({
    id: "13-14_apr_01",
    monthIndex: 4,
    sequenceIndex: 1,
    phase: "organizacao_funcional_do_jogo",
    stageLabel: "bloqueio inicial com cobertura e contra-ataque simples",
    complexityLevel: "moderado_alto",
    alreadyIntroduced: ["defense_control_intro", "coverage_intro", "attack_arm_intro"],
    alreadyPracticedContexts: ["application_game", "reduced_court"],
    nextStep: ["block_marking_intro", "attack_arm_intro"],
    pedagogicalConstraints: [
      "tratar bloqueio como referência inicial de frente de rede",
      "não cobrar sistema formal de bloqueio",
      "ligar bloqueio à cobertura e devolução",
    ],
    blockRecommendations: {
      warmup: playfulWarmup(["coverage_intro", "block_marking_intro"], ["trio_work", "continuity_game"], "trio"),
      main: guidedMain(["block_marking_intro", "attack_arm_intro"], ["application_game", "reduced_court"], "desafio_curto", "equipes_reduzidas", "moderada_alta"),
      cooldown: closingBlock([], []),
    },
    source: {
      methodology: "instituto_compartilhar",
      sourceLabel: "Mini 4x4 — abril",
      sourceRef: "frente de rede inicial e organização simples",
    },
  }),
  make13to14Stage({
    id: "13-14_may_01",
    monthIndex: 5,
    sequenceIndex: 1,
    phase: "organizacao_funcional_do_jogo",
    stageLabel: "serviço, recepção e organização de ataque no mini 4x4",
    complexityLevel: "moderado_alto",
    alreadyIntroduced: ["block_marking_intro", "receive_direction", "attack_arm_intro"],
    alreadyPracticedContexts: ["application_game", "adapted_rules"],
    nextStep: ["underhand_serve_target", "three_action_continuity"],
    pedagogicalConstraints: [
      "dar mais peso à construção após o saque",
      "não reduzir a aula a execução isolada",
      "manter leitura funcional do espaço",
    ],
    blockRecommendations: {
      warmup: playfulWarmup(["underhand_serve_target", "receive_direction"], ["simple_target", "pair_work"], "dupla"),
      main: guidedMain(["underhand_serve_target", "three_action_continuity"], ["application_game", "reduced_court"], "mini_jogo", "equipes_reduzidas", "moderada_alta"),
      cooldown: closingBlock([], []),
    },
    source: {
      methodology: "instituto_compartilhar",
      sourceLabel: "Mini 4x4 — maio",
      sourceRef: "construção após saque e organização de ataque",
    },
  }),
  make13to14Stage({
    id: "13-14_jun_01",
    monthIndex: 6,
    sequenceIndex: 1,
    phase: "consolidacao_pre_formal",
    stageLabel: "mini 4x4 com transições mais estáveis",
    complexityLevel: "moderado_alto",
    alreadyIntroduced: ["three_action_continuity", "block_marking_intro", "coverage_intro"],
    alreadyPracticedContexts: ["application_game", "reduced_court", "continuity_game"],
    nextStep: ["three_action_continuity", "attack_arm_intro"],
    pedagogicalConstraints: [
      "consolidar transições antes de qualquer passo ao formal",
      "usar estabilidade das ações como critério",
      "não pular para 6x6",
    ],
    blockRecommendations: {
      warmup: playfulWarmup(["receive_direction", "coverage_intro"], ["trio_work", "continuity_game"], "trio"),
      main: guidedMain(["three_action_continuity", "attack_arm_intro"], ["application_game", "reduced_court"], "mini_jogo", "equipes_reduzidas", "moderada_alta"),
      cooldown: closingBlock([], []),
    },
    source: {
      methodology: "instituto_compartilhar",
      sourceLabel: "Mini 4x4 — junho",
      sourceRef: "mais estabilidade de transição no 4x4",
    },
  }),
  make13to14Stage({
    id: "13-14_jul_01",
    monthIndex: 7,
    sequenceIndex: 1,
    phase: "retomada_e_revisao",
    stageLabel: "retomada funcional do mini 4x4",
    complexityLevel: "moderado",
    alreadyIntroduced: ["receive_direction", "three_action_continuity", "coverage_intro"],
    alreadyPracticedContexts: ["application_game", "adapted_rules"],
    nextStep: ["defense_control_intro", "attack_arm_intro"],
    pedagogicalConstraints: [
      "retomar organização sem perder identidade da faixa",
      "usar revisão funcional e não regressão excessiva",
      "preservar o contexto do 4x4",
    ],
    blockRecommendations: {
      warmup: playfulWarmup(["receive_direction", "set_continuity"], ["trio_work", "simple_target"], "trio"),
      main: guidedMain(["defense_control_intro", "attack_arm_intro"], ["application_game", "reduced_court"], "estacao", "equipes_reduzidas", "moderada"),
      cooldown: closingBlock([], []),
    },
    source: {
      methodology: "instituto_compartilhar",
      sourceLabel: "Mini 4x4 — julho",
      sourceRef: "retomada funcional após pausa",
    },
  }),
  make13to14Stage({
    id: "13-14_aug_01",
    monthIndex: 8,
    sequenceIndex: 1,
    phase: "consolidacao_pre_formal",
    stageLabel: "mini 4x4 mais fluido com cobertura e ataque mais estáveis",
    complexityLevel: "moderado_alto",
    alreadyIntroduced: ["defense_control_intro", "coverage_intro", "attack_arm_intro"],
    alreadyPracticedContexts: ["application_game", "reduced_court"],
    nextStep: ["coverage_intro", "block_marking_intro"],
    pedagogicalConstraints: [
      "pedir mais fluidez entre ações",
      "manter leitura funcional do jogo",
      "ainda não migrar para organização formal completa",
    ],
    blockRecommendations: {
      warmup: playfulWarmup(["coverage_intro", "attack_arm_intro"], ["trio_work", "continuity_game"], "trio"),
      main: guidedMain(["coverage_intro", "block_marking_intro"], ["application_game", "reduced_court"], "mini_jogo", "equipes_reduzidas", "moderada_alta"),
      cooldown: closingBlock([], []),
    },
    source: {
      methodology: "instituto_compartilhar",
      sourceLabel: "Mini 4x4 — agosto",
      sourceRef: "mais fluidez antes da aplicação ampliada",
    },
  }),
  make13to14Stage({
    id: "13-14_sep_01",
    monthIndex: 9,
    sequenceIndex: 1,
    phase: "aplicacao_ampliada",
    stageLabel: "aplicação ampliada do mini 4x4 com organização funcional",
    complexityLevel: "moderado_alto",
    alreadyIntroduced: ["coverage_intro", "block_marking_intro", "attack_arm_intro"],
    alreadyPracticedContexts: ["application_game", "adapted_rules", "reduced_court"],
    nextStep: ["three_action_continuity", "defense_control_intro"],
    pedagogicalConstraints: [
      "integrar construção, cobertura e defesa no jogo",
      "usar desafios de aplicação em vez de sistema formal fechado",
      "preservar 4x4 como referência",
    ],
    blockRecommendations: {
      warmup: playfulWarmup(["receive_direction", "defense_control_intro"], ["trio_work", "continuity_game"], "trio"),
      main: guidedMain(["three_action_continuity", "defense_control_intro"], ["application_game", "reduced_court"], "mini_jogo", "equipes_reduzidas", "moderada_alta"),
      cooldown: closingBlock([], []),
    },
    source: {
      methodology: "instituto_compartilhar",
      sourceLabel: "Mini 4x4 — setembro",
      sourceRef: "aplicação ampliada e organização funcional do jogo",
    },
  }),
  make13to14Stage({
    id: "13-14_oct_01",
    monthIndex: 10,
    sequenceIndex: 1,
    phase: "aplicacao_ampliada",
    stageLabel: "mini 4x4 com leitura funcional mais consistente",
    complexityLevel: "moderado_alto",
    alreadyIntroduced: ["three_action_continuity", "defense_control_intro", "coverage_intro"],
    alreadyPracticedContexts: ["application_game", "reduced_court"],
    nextStep: ["attack_arm_intro", "block_marking_intro"],
    pedagogicalConstraints: [
      "dar mais intencionalidade às decisões sem formalizar demais",
      "ligar leitura funcional ao contexto de mini jogo",
      "evitar salto precoce para 6x6",
    ],
    blockRecommendations: {
      warmup: playfulWarmup(["coverage_intro", "set_continuity"], ["trio_work", "continuity_game"], "trio"),
      main: guidedMain(["attack_arm_intro", "block_marking_intro"], ["application_game", "reduced_court"], "mini_jogo", "equipes_reduzidas", "moderada_alta"),
      cooldown: closingBlock([], []),
    },
    source: {
      methodology: "instituto_compartilhar",
      sourceLabel: "Mini 4x4 — outubro",
      sourceRef: "mais leitura funcional e intenção de jogo",
    },
  }),
  make13to14Stage({
    id: "13-14_nov_01",
    monthIndex: 11,
    sequenceIndex: 1,
    phase: "aplicacao_ampliada",
    stageLabel: "mini 4x4 mais autônomo com desafios combinados",
    complexityLevel: "moderado_alto",
    alreadyIntroduced: ["attack_arm_intro", "block_marking_intro", "coverage_intro"],
    alreadyPracticedContexts: ["application_game", "adapted_rules"],
    nextStep: ["three_action_continuity", "coverage_intro"],
    pedagogicalConstraints: [
      "aumentar autonomia com tarefas combinadas",
      "usar mini 4x4 como ambiente principal",
      "não transformar em treino adulto formal",
    ],
    blockRecommendations: {
      warmup: playfulWarmup(["receive_direction", "attack_arm_intro"], ["trio_work", "continuity_game"], "trio"),
      main: guidedMain(["three_action_continuity", "coverage_intro"], ["application_game", "adapted_rules"], "mini_jogo", "equipes_reduzidas", "moderada_alta"),
      cooldown: closingBlock([], []),
    },
    source: {
      methodology: "instituto_compartilhar",
      sourceLabel: "Mini 4x4 — novembro",
      sourceRef: "autonomia com desafios combinados no 4x4",
    },
  }),
  make13to14Stage({
    id: "13-14_dec_01",
    monthIndex: 12,
    sequenceIndex: 1,
    phase: "fechamento_e_ponte",
    stageLabel: "fechamento do mini 4x4 e ponte consciente para o próximo ciclo",
    complexityLevel: "moderado_alto",
    alreadyIntroduced: ["defense_control_intro", "coverage_intro", "attack_arm_intro", "block_marking_intro"],
    alreadyPracticedContexts: ["application_game", "adapted_rules", "reduced_court"],
    nextStep: ["three_action_continuity", "attack_arm_intro"],
    pedagogicalConstraints: [
      "fechar o ano sem antecipar formalização total",
      "usar avaliação pedagógica leve e contextual",
      "manter clareza sobre a ponte para o próximo ciclo",
    ],
    blockRecommendations: {
      warmup: playfulWarmup(["receive_direction", "set_continuity"], ["trio_work", "continuity_game"], "trio"),
      main: guidedMain(["three_action_continuity", "attack_arm_intro"], ["application_game", "reduced_court"], "mini_jogo", "equipes_reduzidas", "moderada_alta"),
      cooldown: closingBlock([], []),
    },
    source: {
      methodology: "instituto_compartilhar",
      sourceLabel: "Mini 4x4 — dezembro",
      sourceRef: "fechamento anual e ponte consciente para o próximo ciclo",
    },
  }),
];

export const PEDAGOGICAL_PROGRESSION_CATALOG: PedagogicalProgressionStage[] = [
  ...STAGES_08_TO_10,
  ...STAGES_11_TO_12,
  ...STAGES_13_TO_14,
];
