import type { MonthlyPlanningBlueprint } from "../core/models";
import { db } from "./sqlite";

const mapRow = (row: Record<string, unknown>): MonthlyPlanningBlueprint => ({
  id: String(row.id ?? ""),
  classId: String(row.classId ?? ""),
  cycleId: String(row.cycleId ?? "") || undefined,
  year: Number(row.year ?? 0),
  month: Number(row.month ?? 0),
  title: String(row.title ?? ""),
  macroIntent: String(row.macroIntent ?? ""),
  pedagogicalProgression: String(row.pedagogicalProgression ?? "[]"),
  weeklyFocusDistributionJson: String(
    row.weeklyFocusDistributionJson ?? "{}",
  ),
  constraintsJson: String(row.constraintsJson ?? "{}"),
  contextSnapshotJson: String(row.contextSnapshotJson ?? "{}"),
  generationModelVersion: String(row.generationModelVersion ?? ""),
  generationVersion: Number(row.generationVersion ?? 1),
  syncStatus:
    row.syncStatus === "out_of_sync" || row.syncStatus === "regenerating"
      ? row.syncStatus
      : "in_sync",
  lastAutoGeneratedAt: String(row.lastAutoGeneratedAt ?? ""),
  lastManualEditedAt: String(row.lastManualEditedAt ?? ""),
  createdAt: String(row.createdAt ?? ""),
  updatedAt: String(row.updatedAt ?? ""),
});

export const getMonthlyPlanningBlueprint = async (params: {
  classId: string;
  year: number;
  month: number;
  cycleId?: string | null;
}): Promise<MonthlyPlanningBlueprint | null> => {
  const cycleId = String(params.cycleId ?? "").trim();
  const sql = cycleId
    ? `SELECT * FROM monthly_planning_blueprints
       WHERE classId = ? AND year = ? AND month = ? AND cycleId = ?
       LIMIT 1`
    : `SELECT * FROM monthly_planning_blueprints
       WHERE classId = ? AND year = ? AND month = ?
       ORDER BY updatedAt DESC
       LIMIT 1`;
  const bindings = cycleId
    ? [params.classId, params.year, params.month, cycleId]
    : [params.classId, params.year, params.month];
  const row = await db.getFirstAsync<Record<string, unknown>>(sql, bindings);
  return row ? mapRow(row) : null;
};

export const upsertMonthlyPlanningBlueprint = async (
  blueprint: MonthlyPlanningBlueprint,
): Promise<void> => {
  await db.runAsync(
    `INSERT OR REPLACE INTO monthly_planning_blueprints
      (id, classId, cycleId, year, month, title, macroIntent,
       pedagogicalProgression, weeklyFocusDistributionJson, constraintsJson,
       contextSnapshotJson, generationModelVersion, generationVersion,
       syncStatus, lastAutoGeneratedAt, lastManualEditedAt, createdAt, updatedAt)
     VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
    [
      blueprint.id,
      blueprint.classId,
      blueprint.cycleId ?? "",
      blueprint.year,
      blueprint.month,
      blueprint.title,
      blueprint.macroIntent,
      blueprint.pedagogicalProgression,
      blueprint.weeklyFocusDistributionJson,
      blueprint.constraintsJson,
      blueprint.contextSnapshotJson,
      blueprint.generationModelVersion,
      blueprint.generationVersion,
      blueprint.syncStatus,
      blueprint.lastAutoGeneratedAt,
      blueprint.lastManualEditedAt,
      blueprint.createdAt,
      blueprint.updatedAt,
    ],
  );
};
