import type {
  DailyLessonPlan,
  SessionComponent,
  SessionEnvironment,
  SessionPrimaryComponent,
} from "../core/models";
import { db } from "./sqlite";

type DailyLessonPlanRow = {
  id: string;
  classId: string;
  weeklyPlanId: string;
  date: string;
  dayOfWeek: number;
  title: string;
  blocksJson: string;
  sessionComponentsJson: string;
  sessionEnvironment: string;
  sessionPrimaryComponent: string;
  warmup: string;
  mainPart: string;
  cooldown: string;
  observations: string;
  generationVersion: number;
  derivedFromWeeklyVersion: number;
  generationModelVersion: string;
  generationContextSnapshotJson: string;
  syncStatus: string;
  outOfSyncReasonsJson: string;
  manualOverridesJson: string;
  manualOverrideMaskJson: string;
  lastAutoGeneratedAt: string;
  lastManualEditedAt: string;
  createdAt: string;
  updatedAt: string;
};

const parseSessionComponents = (value: string | undefined): SessionComponent[] | undefined => {
  try {
    const parsed = JSON.parse(value ?? "[]");
    return Array.isArray(parsed) ? (parsed as SessionComponent[]) : undefined;
  } catch {
    return undefined;
  }
};

const parseSessionEnvironment = (value: string | undefined): SessionEnvironment | undefined => {
  switch (value) {
    case "quadra":
    case "academia":
    case "mista":
    case "preventiva":
      return value;
    default:
      return undefined;
  }
};

const parseSessionPrimaryComponent = (
  value: string | undefined,
): SessionPrimaryComponent | undefined => {
  switch (value) {
    case "tecnico_tatico":
    case "fisico_integrado":
    case "resistido":
    case "preventivo":
    case "misto_transferencia":
      return value;
    default:
      return undefined;
  }
};

const mapDailyLessonPlanRow = (row: DailyLessonPlanRow): DailyLessonPlan => ({
  id: row.id,
  classId: row.classId,
  weeklyPlanId: row.weeklyPlanId,
  date: row.date,
  dayOfWeek: row.dayOfWeek,
  title: row.title,
  blocksJson: row.blocksJson,
  sessionComponents: parseSessionComponents(row.sessionComponentsJson),
  sessionEnvironment: parseSessionEnvironment(row.sessionEnvironment),
  sessionPrimaryComponent: parseSessionPrimaryComponent(row.sessionPrimaryComponent),
  warmup: row.warmup,
  mainPart: row.mainPart,
  cooldown: row.cooldown,
  observations: row.observations,
  generationVersion: row.generationVersion,
  derivedFromWeeklyVersion: row.derivedFromWeeklyVersion,
  generationModelVersion: row.generationModelVersion,
  generationContextSnapshotJson: row.generationContextSnapshotJson,
  syncStatus:
    row.syncStatus === "out_of_sync" || row.syncStatus === "overridden" || row.syncStatus === "stale_parent"
      ? row.syncStatus
      : "in_sync",
  outOfSyncReasonsJson: row.outOfSyncReasonsJson,
  manualOverridesJson: row.manualOverridesJson,
  manualOverrideMaskJson: row.manualOverrideMaskJson,
  lastAutoGeneratedAt: row.lastAutoGeneratedAt,
  lastManualEditedAt: row.lastManualEditedAt,
  createdAt: row.createdAt,
  updatedAt: row.updatedAt,
});

const buildWeekIdPlaceholders = (ids: string[]) => ids.map(() => "?").join(",");

export async function listDailyLessonPlansByWeekIds(weeklyPlanIds: string[]) {
  if (!weeklyPlanIds.length) return [] as DailyLessonPlan[];

  const placeholders = buildWeekIdPlaceholders(weeklyPlanIds);
  try {
    const rows = await db.getAllAsync<DailyLessonPlanRow>(
      `SELECT * FROM daily_lesson_plans
       WHERE weeklyPlanId IN (${placeholders})
       ORDER BY date ASC`,
      weeklyPlanIds
    );

    return rows.map(mapDailyLessonPlanRow);
  } catch (error) {
    // Gracefully handle missing table or db unavailability during development
    console.warn("Failed to load daily lesson plans:", error);
    return [];
  }
}

export async function listRecentDailyLessonPlansByClass(classId: string, limit: number = 12) {
  if (!classId) return [] as DailyLessonPlan[];

  try {
    const rows = await db.getAllAsync<DailyLessonPlanRow>(
      `SELECT * FROM daily_lesson_plans
       WHERE classId = ?
       ORDER BY date DESC
       LIMIT ?`,
      [classId, Math.max(1, Math.floor(limit))]
    );

    return rows.map(mapDailyLessonPlanRow);
  } catch (error) {
    console.warn("Failed to load recent daily lesson plans:", error);
    return [];
  }
}

export async function getDailyLessonPlanByWeekAndDate(weeklyPlanId: string, date: string) {
  try {
    const row = await db.getFirstAsync<DailyLessonPlanRow>(
      `SELECT * FROM daily_lesson_plans
       WHERE weeklyPlanId = ? AND date = ?
       LIMIT 1`,
      [weeklyPlanId, date]
    );

    return row ? mapDailyLessonPlanRow(row) : null;
  } catch (error) {
    console.warn("Failed to load daily lesson plan:", error);
    return null;
  }
}

export async function upsertDailyLessonPlan(plan: DailyLessonPlan) {
  try {
    await db.runAsync(
      `INSERT OR REPLACE INTO daily_lesson_plans (
        id, classId, weeklyPlanId, date, dayOfWeek, title,
        blocksJson,
        sessionComponentsJson, sessionEnvironment, sessionPrimaryComponent,
        warmup, mainPart, cooldown, observations,
        generationVersion, derivedFromWeeklyVersion,
        generationModelVersion, generationContextSnapshotJson,
        syncStatus, outOfSyncReasonsJson,
        manualOverridesJson, manualOverrideMaskJson,
        lastAutoGeneratedAt, lastManualEditedAt,
        createdAt, updatedAt
      ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      [
        plan.id,
        plan.classId,
        plan.weeklyPlanId,
        plan.date,
        plan.dayOfWeek,
        plan.title,
        plan.blocksJson ?? "[]",
        JSON.stringify(plan.sessionComponents ?? []),
        plan.sessionEnvironment ?? "",
        plan.sessionPrimaryComponent ?? "",
        plan.warmup,
        plan.mainPart,
        plan.cooldown,
        plan.observations,
        plan.generationVersion ?? 1,
        plan.derivedFromWeeklyVersion ?? 1,
        plan.generationModelVersion ?? "",
        plan.generationContextSnapshotJson ?? "{}",
        plan.syncStatus ?? "in_sync",
        plan.outOfSyncReasonsJson ?? "[]",
        plan.manualOverridesJson ?? "{}",
        plan.manualOverrideMaskJson ?? "[]",
        plan.lastAutoGeneratedAt ?? plan.updatedAt,
        plan.lastManualEditedAt ?? plan.updatedAt,
        plan.createdAt,
        plan.updatedAt,
      ]
    );
  } catch (error) {
    console.warn("Failed to upsert daily lesson plan:", error);
  }
}

export async function markDailyLessonPlansOutOfSyncByWeek(
  weeklyPlanId: string,
  reason: string = "weekly_plan_changed"
) {
  try {
    await db.runAsync(
      `UPDATE daily_lesson_plans
       SET syncStatus = 'out_of_sync',
           outOfSyncReasonsJson = ?,
           updatedAt = ?
       WHERE weeklyPlanId = ?`,
      [JSON.stringify([reason]), new Date().toISOString(), weeklyPlanId]
    );
  } catch (error) {
    console.warn("Failed to mark daily lesson plans out of sync:", error);
  }
}
