export const ptBR = {
  session: {
    title: "Aula do dia",
    tabs: {
      training: "Treino",
      report: "Fazer relatório",
      scouting: "Scouting",
    },
    warmup: "Aquecimento",
    main: "Parte principal",
    cooldown: "Volta à calma",
    noPlanNotice: "",
    emptyPlan: {
      title: "Sem plano aplicado",
      description: "Escolha um treino salvo ou crie um novo plano de aula.",
      applyTraining: "Aplicar treino",
      createPlan: "Criar plano",
    },
    actions: {
      startTraining: "Fazer chamada",
      export: "Exportar",
      generateAutomatic: "Gerar automático",
      generateAutomaticPlan: "Gerar plano automático",
      applySavedTraining: "Aplicar treino salvo",
      importPlan: "Importar plano",
      apply: "Aplicar",
      cancel: "Cancelar",
      save: "Salvar",
      saveChanges: "Salvar alterações",
      generateReport: "Gerar relatório",
      saving: "Salvando...",
      opening: "Abrindo...",
      takePhoto: "Tirar foto",
      gallery: "Galeria",
      replaceCamera: "Substituir (câmera)",
      replaceGallery: "Substituir (galeria)",
      remove: "Remover",
    },
    report: {
      title: "Relatório da aula",
      noReportYet: "Nenhum relatório registrado ainda.",
      editingExisting: "Editando relatório existente",
      pse: "PSE (0-10)",
      technique: "Técnica geral",
      participants: "Número de participantes",
      participantsPlaceholder: "Ex: 12",
      activity: "Atividade",
      activityPlaceholder: "Resumo da atividade principal",
      conclusion: "Conclusão",
      conclusionPlaceholder: "Observações finais da aula",
      photos: "Fotos",
      previewAppliedTraining: "Preview do treino aplicado",
      clearToApplyHint: "Limpe o campo para aplicar do treino.",
      photoActionTitle: "Foto do relatório",
      photoActionSubtitle: "Escolha uma ação",
    },
    decisionOverride: {
      title: "Decisão do(a) professor(a)",
      description: "Registre a decisão final desta sessão com base na sua leitura pedagógica.",
      reason: "Motivo da decisão",
      optionalNote: "Observação (opcional)",
      saveFinalDecision: "Salvar decisão final",
    },
    viewSuggestionLogic: "Ver lógica da sugestão",
    hideSuggestionLogic: "Ocultar lógica da sugestão",
    objective: "Objetivo da aula",
    applyManualAdjustment: "Aplicar ajuste manual",
    alerts: {
      saveFailedTitle: "Falha ao salvar",
      exportPdfFailedTitle: "Falha ao exportar PDF",
      tryAgain: "Tente novamente.",
    },
    success: {
      reportSaved: "Relatório salvo com sucesso.",
      blockUpdated: "Bloco atualizado com sucesso.",
      planVersionCreated: "Nova versão do plano criada com sucesso.",
      planCreated: "Plano criado com sucesso.",
      methodologyAdjusted: "Nova versão criada com metodologia ajustada.",
      suggestionApplied: "Nova versão criada com sugestão aplicada.",
      decisionSaved: "Decisão final do(a) professor(a) registrada com sucesso.",
      decisionAdjusted: "Ajuste manual do(a) professor(a) registrado com sucesso.",
      pdfGenerated: "PDF gerado com sucesso.",
      reportGenerated: "Relatório gerado com sucesso.",
      scoutingSaved: "Scouting salvo com sucesso.",
      textImproved: "Texto melhorado e aplicado.",
    },
    errors: {
      photoSelectFailed: "Não foi possível selecionar a foto.",
      textImproveFailed: "Não foi possível melhorar o texto agora.",
      reportSaveFailed: "Não foi possível salvar o relatório.",
      planGenerateFailed: "Não foi possível gerar o plano agora.",
      blockSaveFailed: "Não foi possível salvar o bloco.",
      alternativeMethodologyFailed: "Não foi possível aplicar a metodologia alternativa.",
      reapplySuggestionFailed: "Não foi possível reaplicar a sugestão.",
      decisionSaveFailed: "Não foi possível salvar o ajuste de decisão.",
      pdfGenerateFailed: "Não foi possível gerar o PDF.",
      reportGenerateFailed: "Não foi possível gerar o relatório.",
      scoutingSaveFailed: "Não foi possível salvar o scouting.",
    },
    suggestionLogic: {
      methodology: "Metodologia",
      rationale: "Justificativa",
      sessionFocus: "Foco",
      progressionCriterion: "Critério principal",
      adherenceScore: "Score de aderência",
      lastOverride: "Ajuste recente do professor",
      noData: "Sem dado",
    },
  },
  scouting: {
    title: "Scouting (0-1-2)",
    operationHint: "Toque para somar e pressione para remover.",
    totalActions: "Total de ações",
    showGuide: "Ver guia completo",
    hideGuide: "Ocultar guia",
    quickGuideTitle: "Guia completo (0/1/2)",
    modeTrain: "Treino",
    modeMatch: "Jogo",
    averageLabel: "média",
    goodRateLabel: "Boas (2)",
    nextSessionFocus: "Foco da próxima aula",
    minimumActionsHint: "Registre pelo menos 10 ações para sugerir o foco.",
    saveAction: "Salvar scouting",
  },
} as const;
