export const ptBR = {
  common: {
    actions: {
      add: "Adicionar",
      apply: "Aplicar",
      back: "Voltar",
      cancel: "Cancelar",
      close: "Fechar",
      remove: "Remover",
      retry: "Tentar novamente",
      save: "Salvar",
      update: "Atualizar",
    },
    feedback: {
      applying: "Aplicando...",
      generating: "Gerando...",
      generatingPlan: "Gerando plano...",
      loading: "Carregando...",
      reloading: "Recarregando...",
      saving: "Salvando...",
      savingPlan: "Salvando plano...",
    },
    status: {
      updated: "Atualizado",
    },
    accessibility: {
      backFromPrefix: "Voltar de",
      previousClass: "Aula anterior",
      nextClass: "Próxima aula",
    },
  },
  navigation: {
    back: "Voltar",
  },
  actions: {
    add: "Adicionar",
    apply: "Aplicar",
    back: "Voltar",
    cancel: "Cancelar",
    close: "Fechar",
    remove: "Remover",
    retry: "Tentar novamente",
    save: "Salvar",
    update: "Atualizar",
  },
  forms: {
    required: "Obrigatório",
    select: "Selecione",
  },
  loading: {
    title: "Carregando",
    generic: "Carregando...",
    preparingScreen: "Preparando a tela.",
    routes: {
      absenceNotices: "Carregando avisos...",
      achievements: "Carregando conquistas...",
      agenda: "Carregando agenda...",
      assistant: "Carregando assistente...",
      calendar: "Carregando calendário...",
      classes: "Carregando turmas...",
      communication: "Carregando comunicação...",
      dashboard: "Carregando painel...",
      events: "Carregando eventos...",
      exercises: "Carregando exercícios...",
      management: "Carregando gestão...",
      members: "Carregando membros...",
      nfc: "Carregando NFC...",
      periodization: "Carregando periodização...",
      planning: "Carregando planejamento...",
      profile: "Carregando perfil...",
      reports: "Carregando relatórios...",
      students: "Carregando alunos...",
    },
  },
  errors: {
    appCrashed: "Algo deu errado",
    startupTitle: "Ocorreu um erro ao iniciar",
    startupDescription: "Tente novamente. Se persistir, reinicie o app.",
    unknown: "Erro desconhecido",
  },
  emptyStates: {
    noData: "Nenhum dado encontrado.",
    noResults: "Nenhum resultado encontrado.",
  },
  session: {
    title: "Aula do dia",
    tabs: {
      training: "Treino",
      report: "Fazer relatório",
      scouting: "Scouting",
    },
    warmup: "Aquecimento",
    main: "Parte principal",
    cooldown: "Volta à calma",
    noPlanNotice: "",
    emptyPlan: {
      title: "Sem plano aplicado",
      description: "Escolha um treino salvo ou crie um novo plano de aula.",
      applyTraining: "Aplicar treino",
      createPlan: "Criar plano",
      hidePlans: "Ocultar planos",
      savedPlansTitle: "Planos salvos desta turma",
      savedPlansDescription: "Escolha um plano já salvo para aplicar somente nesta aula.",
      applyThisDay: "Aplicar neste dia",
      noSavedPlans: "Esta turma ainda não tem planos finais salvos para reutilizar aqui.",
    },
    actions: {
      startTraining: "Fazer chamada",
      export: "Exportar",
      generateAutomatic: "Gerar automático",
      generateAutomaticPlan: "Gerar plano automático",
      applySavedTraining: "Aplicar treino salvo",
      importPlan: "Importar plano",
      apply: "Aplicar",
      cancel: "Cancelar",
      save: "Salvar",
      saveChanges: "Salvar alterações",
      generateReport: "Gerar relatório",
      saving: "Salvando...",
      opening: "Abrindo...",
      takePhoto: "Tirar foto",
      gallery: "Galeria",
      replaceCamera: "Substituir (câmera)",
      replaceGallery: "Substituir (galeria)",
      remove: "Remover",
    },
    report: {
      title: "Relatório da aula",
      noReportYet: "Nenhum relatório registrado ainda.",
      editingExisting: "Editando relatório existente",
      pse: "PSE (0-10)",
      technique: "Técnica geral",
      participants: "Número de participantes",
      participantsPlaceholder: "Ex: 12",
      activity: "Atividade",
      activityPlaceholder: "Resumo da atividade principal",
      conclusion: "Conclusão",
      conclusionPlaceholder: "Observações finais da aula",
      photos: "Fotos",
      previewAppliedTraining: "Preview do treino aplicado",
      clearToApplyHint: "Limpe o campo para aplicar do treino.",
      photoActionTitle: "Foto do relatório",
      photoActionSubtitle: "Escolha uma ação",
    },
    decisionOverride: {
      title: "Decisão do(a) professor(a)",
      description: "Registre a decisão final desta sessão com base na sua leitura pedagógica.",
      reason: "Motivo da decisão",
      optionalNote: "Observação (opcional)",
      saveFinalDecision: "Salvar decisão final",
    },
    objective: "Objetivo da aula",
    objectiveActions: {
      edit: "Editar objetivo",
      save: "Salvar objetivo",
      saving: "Salvando",
    },
    unavailable: {
      classNotFoundTitle: "Turma não encontrada",
      loadFailedTitle: "Falha ao carregar a aula",
      classNotFoundDescription:
        "Esta turma não está disponível no ambiente local ou a sessão expirou. Volte para turmas e selecione uma turma ativa.",
      loadFailedDescription: "Não foi possível carregar os dados da Aula do Dia.",
    },
    alerts: {
      saveFailedTitle: "Falha ao salvar",
      exportPdfFailedTitle: "Falha ao exportar PDF",
      tryAgain: "Tente novamente.",
    },
    success: {
      reportSaved: "Relatório salvo com sucesso.",
      blockUpdated: "Bloco atualizado com sucesso.",
      planVersionCreated: "Nova versão do plano criada com sucesso.",
      planCreated: "Plano criado com sucesso.",
      methodologyAdjusted: "Nova versão criada com metodologia ajustada.",
      suggestionApplied: "Nova versão criada com sugestão aplicada.",
      decisionSaved: "Decisão final do(a) professor(a) registrada com sucesso.",
      decisionAdjusted: "Ajuste manual do(a) professor(a) registrado com sucesso.",
      pdfGenerated: "PDF gerado com sucesso.",
      reportGenerated: "Relatório gerado com sucesso.",
      scoutingSaved: "Scouting salvo com sucesso.",
      textImproved: "Texto melhorado e aplicado.",
    },
    errors: {
      photoSelectFailed: "Não foi possível selecionar a foto.",
      textImproveFailed: "Não foi possível melhorar o texto agora.",
      reportSaveFailed: "Não foi possível salvar o relatório.",
      planGenerateFailed: "Não foi possível gerar o plano agora.",
      blockSaveFailed: "Não foi possível salvar o bloco.",
      alternativeMethodologyFailed: "Não foi possível aplicar a metodologia alternativa.",
      reapplySuggestionFailed: "Não foi possível reaplicar a sugestão.",
      decisionSaveFailed: "Não foi possível salvar o ajuste de decisão.",
      pdfGenerateFailed: "Não foi possível gerar o PDF.",
      reportGenerateFailed: "Não foi possível gerar o relatório.",
      scoutingSaveFailed: "Não foi possível salvar o scouting.",
    },
  },
  scouting: {
    title: "Scouting (0-1-2)",
    operationHint: "Toque para somar e pressione para remover.",
    totalActions: "Total de ações",
    showGuide: "Ver guia completo",
    hideGuide: "Ocultar guia",
    quickGuideTitle: "Guia completo (0/1/2)",
    modeTrain: "Treino",
    modeMatch: "Jogo",
    averageLabel: "média",
    goodRateLabel: "Boas (2)",
    nextSessionFocus: "Foco da próxima aula",
    minimumActionsHint: "Registre pelo menos 10 ações para sugerir o foco.",
    saveAction: "Salvar scouting",
  },
} as const;
