import { createElement, useState, type ReactNode } from "react";
import { UnifiedAssistantProvider } from "../../../assistant/UnifiedAssistantProvider";
import { buildOperationalContext } from "../../../copilot/operational-context";
import { act, renderHook } from "@testing-library/react-native";
import AsyncStorage from "@react-native-async-storage/async-storage";
import { PlanningAssistantProvider, usePlanningAssistant } from "../PlanningAssistant";
import { requestAssistantConversation } from "../../../api/ai";
jest.mock("../../../auth/auth", () => ({ useAuth: () => ({ session: { user: { id: "provider-coach" } } }) }));
jest.mock("../../../api/ai", () => ({ requestAssistantConversation: jest.fn() }));
jest.mock("../../../assistant/components/AssistantMessages", () => ({ AssistantMessages: () => null }));
jest.mock("../../../assistant/components/AssistantComposer", () => ({ AssistantComposer: () => null }));
jest.mock("../../../assistant/components/AssistantPending", () => ({ AssistantPending: () => null }));
jest.mock("../../../ui/ModalSheet", () => ({ ModalSheet: () => null }));
jest.mock("../../../ui/Pressable", () => ({ Pressable: () => null }));
beforeEach(async () => { jest.clearAllMocks(); await AsyncStorage.clear(); });
test("one controller preserves text, request and history across editor and lesson contexts", async () => {
  let resolve!: (value: unknown) => void;
  (requestAssistantConversation as jest.Mock).mockReturnValue(new Promise(done => { resolve = done; }));
  const Wrapper = ({ children }: { children: ReactNode }) => {
    const [open,setOpen]=useState(false);
    const snapshot=buildOperationalContext({screen:"periodization",contextTitle:"Planejamento",contextSubtitle:"",signals:[],selectedSignalId:null,regulationUpdates:[],regulationRuleSets:[],history:[]}).snapshot;
    return createElement(UnifiedAssistantProvider,{userId:"provider-coach",organizationId:"provider-org",snapshot,lesson:null,open,toggle:()=>setOpen(value=>!value)},createElement(PlanningAssistantProvider, { organizationId: "provider-org", classId: "provider-class" },children));
  };
  const hook = renderHook(() => usePlanningAssistant()!, { wrapper: Wrapper });
  expect(hook.result.current.open).toBe(false);
  act(() => { hook.result.current.chat.setInput("Como distribuir a carga?"); hook.result.current.toggle(); hook.result.current.setSelection({ month: "2026-09", weekNumber: 39 }); });
  act(() => hook.result.current.setEditor({ step: "Modelo de carga", draft: { intensityMax: 6 } }));
  expect(hook.result.current.chat.input).toBe("Como distribuir a carga?");
  expect(requestAssistantConversation).not.toHaveBeenCalled();
  let pending!: Promise<void>;
  act(() => { pending = hook.result.current.chat.send(); });
  act(() => { hook.result.current.setEditor(null); hook.result.current.setLesson({ draft: { title: "Nova escolha" } }); });
  expect(hook.result.current.surface).toBe("lesson");
  expect(hook.result.current.chat.busy).toBe(true);
  await act(async () => { resolve({ reply: "Orientação sem aplicar", planningContextVersion: 1 }); await pending; });
  expect(hook.result.current.chat.messages.at(-1)?.planningContext).toMatchObject({ surface: "editor", step: "Modelo de carga", draft: { intensityMax: 6 } });
  act(() => hook.result.current.setLesson(null));
  expect(hook.result.current.surface).toBe("workspace");
  expect(hook.result.current.chat.messages.at(-1)?.content).toBe("Orientação sem aplicar");
  expect(requestAssistantConversation).toHaveBeenCalledTimes(1);
});
