import { act, renderHook, waitFor } from "@testing-library/react-native";
import AsyncStorage from "@react-native-async-storage/async-storage";
import { useClassDiagnostic } from "../useClassDiagnostic";
import { ProfileConflictError, requestClassProfile } from "../../../api/class-pedagogical-profile";
jest.mock("../../../auth/auth", () => ({ useAuth: () => ({ session: { user: { id: "coach" } } }) }));
jest.mock("../../../api/class-pedagogical-profile", () => ({ requestClassProfile: jest.fn(), ProfileConflictError: class ProfileConflictError extends Error {} }));
const ready = { profile: null, messages: [], revisions: [], suggestions: [], status: "ready", revisionId: null };
const request = requestClassProfile as jest.Mock;
beforeEach(async () => { jest.clearAllMocks(); await AsyncStorage.clear(); request.mockResolvedValue(ready); });

test("network failure preserves an identity-scoped draft and retries the same id after reopening", async () => {
  const first = renderHook(() => useClassDiagnostic("org", "raposas"));
  await waitFor(() => expect(first.result.current.loading).toBe(false));
  act(() => first.result.current.setInput("Joga 6x6 com um quique"));
  request.mockRejectedValueOnce(new Error("Sem conexão"));
  await act(async () => { await first.result.current.send(); });
  const original = first.result.current.pending;
  expect(first.result.current.error).toContain("conexão");
  expect(first.result.current.snapshot?.status).toBe("ready");
  first.unmount();
  const reopened = renderHook(() => useClassDiagnostic("org", "raposas"));
  await waitFor(() => expect(reopened.result.current.loading).toBe(false));
  expect(reopened.result.current.pending?.requestId).toBe(original?.requestId);
  request.mockResolvedValueOnce({ ...ready, status: "saved" });
  await act(async () => { await reopened.result.current.retry(); });
  expect(request.mock.calls.at(-1)[2].requestId).toBe(original?.requestId);
  expect(reopened.result.current.input).toBe("");
  const other = renderHook(() => useClassDiagnostic("other-org", "raposas"));
  await waitFor(() => expect(other.result.current.loading).toBe(false));
  expect(other.result.current.input).toBe(""); expect(other.result.current.pending).toBeUndefined();
});
test("saved-but-uninterpreted reports stay visible and cannot be sent again with a new id", async () => {
  const { result } = renderHook(() => useClassDiagnostic("org", "raposas"));
  await waitFor(() => expect(result.current.loading).toBe(false));
  act(() => result.current.setInput("Bom domínio dos fundamentos"));
  request.mockResolvedValueOnce({ ...ready, status: "pending", messages: [{ id: "message", content: "Bom domínio dos fundamentos", author_id: "coach", status: "pending", reply: "", question: "" }] });
  await act(async () => { await result.current.send(); });
  expect(result.current.messages).toHaveLength(1);
  const calls = request.mock.calls.length;
  await act(async () => { await result.current.send(); });
  expect(request).toHaveBeenCalledTimes(calls);
  expect(result.current.pending).toBeDefined();
});
test("a stale selector refreshes but requires a new teacher choice", async () => {
  const { result } = renderHook(() => useClassDiagnostic("org", "raposas"));
  await waitFor(() => expect(result.current.loading).toBe(false));
  request.mockRejectedValueOnce(new ProfileConflictError("O perfil mudou"));
  await act(async () => { await result.current.command({ action: "selectors", gameFormat: "4x4" }); });
  expect(result.current.pending).toBeUndefined();
  expect(result.current.error).toContain("mudou");
  expect(request.mock.calls.at(-1)[2].action).toBe("load");
});
test("late replies do not populate a different class or erase newly typed text", async () => {
  const hook = renderHook(({ cls }) => useClassDiagnostic("org", cls), { initialProps: { cls: "raposas" } });
  await waitFor(() => expect(hook.result.current.loading).toBe(false));
  let finish!: (value: unknown) => void;
  request.mockImplementationOnce(() => new Promise(resolve => { finish = resolve; }));
  act(() => hook.result.current.setInput("primeiro relato"));
  let sent!: Promise<boolean>;
  act(() => { sent = hook.result.current.send(); });
  await waitFor(() => expect(finish).toBeDefined());
  act(() => hook.result.current.setInput("novo texto"));
  await act(async () => { finish({ ...ready, status: "saved" }); await sent; });
  expect(hook.result.current.input).toBe("novo texto");
  hook.rerender({ cls: "outra" });
  await waitFor(() => expect(hook.result.current.loading).toBe(false));
  expect(hook.result.current.input).toBe("");
  expect(hook.result.current.messages).toEqual([]);
});
