import { act, renderHook } from "@testing-library/react-native";
import { useScreenConversation } from "../useScreenConversation";
import { requestAssistantConversation } from "../../../api/ai";
import { buildOperationalContext } from "../../../copilot/operational-context";
import { buildPlanningAssistantContext } from "../../../screens/periodization/application/planning-assistant-context";
jest.mock("../../../api/ai", () => ({ requestAssistantConversation: jest.fn() }));
const request = requestAssistantConversation as jest.Mock;
const snapshot = buildOperationalContext({ screen: "periodization", contextTitle: "", contextSubtitle: "", signals: [], history: [], selectedSignalId: null, regulationRuleSets: [], regulationUpdates: [] }).snapshot;
const context = (month: string) => buildPlanningAssistantContext({ classId: "class", selection: { month, weekNumber: 39 }, surface: "workspace" });
beforeEach(() => jest.clearAllMocks());
test("does not request on navigation; pending reply remains linked to original selection", async () => {
  let resolve!: (value: unknown) => void;
  request.mockReturnValue(new Promise(done => { resolve = done; }));
  const hook = renderHook(({ month }) => useScreenConversation("org", snapshot, "auto", undefined, { classId: "class", lessonAction: "discuss", planningContext: context(month) }), { initialProps: { month: "2026-09" } });
  expect(request).not.toHaveBeenCalled();
  let pending!: Promise<void>;
  act(() => { pending = hook.result.current.send("Analise"); });
  hook.rerender({ month: "2026-10" });
  expect(request).toHaveBeenCalledTimes(1);
  await act(async () => { resolve({ reply: "Orientação", planningContextVersion: 1 }); await pending; });
  expect(hook.result.current.messages.at(-1)?.planningContext?.selection.month).toBe("2026-09");
  expect(hook.result.current.draftTraining).toBeNull();
});
test("failure and old backend preserve text for retry", async () => {
  request.mockResolvedValueOnce({ reply: "Resposta antiga" }).mockResolvedValueOnce({ reply: "Orientação", planningContextVersion: 1 });
  const hook = renderHook(() => useScreenConversation("org", snapshot, "auto", undefined, { lessonAction: "discuss", planningContext: context("2026-09") }));
  await act(async () => { await hook.result.current.send("Minha pergunta"); });
  expect(hook.result.current.input).toBe("Minha pergunta");
  expect(hook.result.current.messages).toEqual([]);
  expect(hook.result.current.error).toContain("backend");
  await act(async () => { await hook.result.current.send(); });
  expect(hook.result.current.messages.at(-1)?.content).toBe("Orientação");
});
test("unmount aborts pending reply and cached scope does not cross identities", async () => {
  let resolve!: (value: unknown) => void;
  request.mockReturnValue(new Promise(done => { resolve = done; }));
  const first = renderHook(() => useScreenConversation("org", snapshot, "auto", "planning:user:org:class", { lessonAction: "discuss", planningContext: context("2026-09") }));
  act(() => first.result.current.setInput("Rascunho"));
  act(() => first.result.current.remember());
  let pending!: Promise<void>;
  act(() => { pending = first.result.current.send(); });
  const signal = request.mock.calls[0][0].signal;
  first.unmount();
  expect(signal.aborted).toBe(true);
  const other = renderHook(() => useScreenConversation("org", snapshot, "auto", "planning:other:org:class"));
  expect(other.result.current.input).toBe("");
  await act(async () => { resolve({ reply: "late", planningContextVersion: 1 }); await pending; });
  expect(other.result.current.messages).toEqual([]);
});
