name: Create Production Builds

jobs:
  build_android:
    name: Build Android (production AAB)
    type: build
    params:
      platform: android
      profile: production

  build_ios:
    name: Build iOS (production)
    type: build
    params:
      platform: ios
      profile: production
