-- CONSULTORIA 2 — Online consultation canonical persistence.
-- Uses text ids to preserve the local pilot/domain ids already generated by the app.

create table if not exists public.consultation_profiles (
  id text primary key,
  organization_id uuid not null references public.organizations(id) on delete cascade,
  student_id text not null references public.students(id) on delete cascade,
  coach_id uuid null,
  goal text not null,
  environment text not null,
  available_equipment jsonb not null default '[]'::jsonb,
  restrictions jsonb not null default '[]'::jsonb,
  injuries jsonb not null default '[]'::jsonb,
  training_days_per_week integer not null,
  preferred_session_duration_min integer null,
  notes text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint consultation_profiles_unique_student unique (organization_id, student_id),
  constraint consultation_profiles_goal_check check (
    goal in ('emagrecimento', 'hipertrofia', 'forca', 'condicionamento', 'saude', 'retorno_atividade', 'outro')
  ),
  constraint consultation_profiles_environment_check check (
    environment in ('casa', 'academia', 'condominio', 'ar_livre', 'misto')
  ),
  constraint consultation_profiles_training_days_check check (training_days_per_week between 1 and 7),
  constraint consultation_profiles_duration_check check (
    preferred_session_duration_min is null or preferred_session_duration_min between 10 and 180
  )
);

create table if not exists public.prescribed_workouts (
  id text primary key,
  organization_id uuid not null references public.organizations(id) on delete cascade,
  student_id text not null references public.students(id) on delete cascade,
  coach_id uuid null,
  title text not null,
  week_start_date date not null,
  day_label text not null,
  objective text not null,
  estimated_duration_min integer null,
  coach_notes text null,
  status text not null default 'draft',
  published_at timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint prescribed_workouts_status_check check (status in ('draft', 'published', 'completed', 'archived')),
  constraint prescribed_workouts_duration_check check (
    estimated_duration_min is null or estimated_duration_min between 10 and 180
  )
);

create table if not exists public.prescribed_exercises (
  id text primary key,
  organization_id uuid not null references public.organizations(id) on delete cascade,
  workout_id text not null references public.prescribed_workouts(id) on delete cascade,
  name text not null,
  order_index integer not null,
  sets integer null,
  reps text null,
  duration_sec integer null,
  rest_sec integer null,
  load text null,
  instructions text null,
  alternatives jsonb not null default '[]'::jsonb,
  media_url text null,
  created_at timestamptz not null default now(),
  constraint prescribed_exercises_sets_check check (sets is null or sets > 0),
  constraint prescribed_exercises_duration_check check (duration_sec is null or duration_sec > 0),
  constraint prescribed_exercises_rest_check check (rest_sec is null or rest_sec >= 0)
);

create table if not exists public.workout_execution_logs (
  id text primary key,
  organization_id uuid not null references public.organizations(id) on delete cascade,
  workout_id text not null references public.prescribed_workouts(id) on delete cascade,
  student_id text not null references public.students(id) on delete cascade,
  completed_at timestamptz not null,
  perceived_exertion integer null,
  pain_level integer null,
  student_feedback text null,
  coach_review_status text not null default 'pending',
  reviewed_at timestamptz null,
  reviewed_by uuid null,
  created_at timestamptz not null default now(),
  constraint workout_execution_logs_pse_check check (perceived_exertion is null or perceived_exertion between 0 and 10),
  constraint workout_execution_logs_pain_check check (pain_level is null or pain_level between 0 and 10),
  constraint workout_execution_logs_review_status_check check (coach_review_status in ('pending', 'reviewed'))
);

create table if not exists public.completed_exercise_logs (
  id text primary key,
  organization_id uuid not null references public.organizations(id) on delete cascade,
  execution_log_id text not null references public.workout_execution_logs(id) on delete cascade,
  exercise_id text null,
  completed boolean not null,
  sets_done integer null,
  reps_done text null,
  load_used text null,
  notes text null,
  created_at timestamptz not null default now(),
  constraint completed_exercise_logs_sets_done_check check (sets_done is null or sets_done >= 0)
);

create index if not exists consultation_profiles_org_student_idx
  on public.consultation_profiles (organization_id, student_id);

create index if not exists prescribed_workouts_org_student_week_idx
  on public.prescribed_workouts (organization_id, student_id, week_start_date desc);

create index if not exists prescribed_workouts_org_status_idx
  on public.prescribed_workouts (organization_id, status, updated_at desc);

create index if not exists prescribed_exercises_workout_idx
  on public.prescribed_exercises (workout_id, order_index asc);

create index if not exists workout_execution_logs_org_student_idx
  on public.workout_execution_logs (organization_id, student_id, completed_at desc);

create index if not exists workout_execution_logs_workout_idx
  on public.workout_execution_logs (workout_id, completed_at desc);

create index if not exists completed_exercise_logs_execution_idx
  on public.completed_exercise_logs (execution_log_id);

alter table public.consultation_profiles enable row level security;
alter table public.prescribed_workouts enable row level security;
alter table public.prescribed_exercises enable row level security;
alter table public.workout_execution_logs enable row level security;
alter table public.completed_exercise_logs enable row level security;

drop policy if exists "consultation_profiles org members select" on public.consultation_profiles;
create policy "consultation_profiles org members select"
  on public.consultation_profiles
  for select
  using (
    exists (
      select 1
      from public.organization_members om
      where om.organization_id = consultation_profiles.organization_id
        and om.user_id = auth.uid()
    )
  );

drop policy if exists "consultation_profiles org members insert" on public.consultation_profiles;
create policy "consultation_profiles org members insert"
  on public.consultation_profiles
  for insert
  with check (
    exists (
      select 1
      from public.organization_members om
      where om.organization_id = consultation_profiles.organization_id
        and om.user_id = auth.uid()
    )
  );

drop policy if exists "consultation_profiles org members update" on public.consultation_profiles;
create policy "consultation_profiles org members update"
  on public.consultation_profiles
  for update
  using (
    exists (
      select 1
      from public.organization_members om
      where om.organization_id = consultation_profiles.organization_id
        and om.user_id = auth.uid()
    )
  )
  with check (
    exists (
      select 1
      from public.organization_members om
      where om.organization_id = consultation_profiles.organization_id
        and om.user_id = auth.uid()
    )
  );

drop policy if exists "consultation_profiles org admins delete" on public.consultation_profiles;
create policy "consultation_profiles org admins delete"
  on public.consultation_profiles
  for delete
  using (public.is_org_admin(consultation_profiles.organization_id));

drop policy if exists "prescribed_workouts org members select" on public.prescribed_workouts;
create policy "prescribed_workouts org members select"
  on public.prescribed_workouts
  for select
  using (
    exists (
      select 1
      from public.organization_members om
      where om.organization_id = prescribed_workouts.organization_id
        and om.user_id = auth.uid()
    )
  );

drop policy if exists "prescribed_workouts org members insert" on public.prescribed_workouts;
create policy "prescribed_workouts org members insert"
  on public.prescribed_workouts
  for insert
  with check (
    exists (
      select 1
      from public.organization_members om
      where om.organization_id = prescribed_workouts.organization_id
        and om.user_id = auth.uid()
    )
  );

drop policy if exists "prescribed_workouts org members update" on public.prescribed_workouts;
create policy "prescribed_workouts org members update"
  on public.prescribed_workouts
  for update
  using (
    exists (
      select 1
      from public.organization_members om
      where om.organization_id = prescribed_workouts.organization_id
        and om.user_id = auth.uid()
    )
  )
  with check (
    exists (
      select 1
      from public.organization_members om
      where om.organization_id = prescribed_workouts.organization_id
        and om.user_id = auth.uid()
    )
  );

drop policy if exists "prescribed_workouts org members delete" on public.prescribed_workouts;
create policy "prescribed_workouts org members delete"
  on public.prescribed_workouts
  for delete
  using (
    exists (
      select 1
      from public.organization_members om
      where om.organization_id = prescribed_workouts.organization_id
        and om.user_id = auth.uid()
    )
  );

drop policy if exists "prescribed_exercises org members select" on public.prescribed_exercises;
create policy "prescribed_exercises org members select"
  on public.prescribed_exercises
  for select
  using (
    exists (
      select 1
      from public.organization_members om
      where om.organization_id = prescribed_exercises.organization_id
        and om.user_id = auth.uid()
    )
  );

drop policy if exists "prescribed_exercises org members insert" on public.prescribed_exercises;
create policy "prescribed_exercises org members insert"
  on public.prescribed_exercises
  for insert
  with check (
    exists (
      select 1
      from public.organization_members om
      where om.organization_id = prescribed_exercises.organization_id
        and om.user_id = auth.uid()
    )
  );

drop policy if exists "prescribed_exercises org members update" on public.prescribed_exercises;
create policy "prescribed_exercises org members update"
  on public.prescribed_exercises
  for update
  using (
    exists (
      select 1
      from public.organization_members om
      where om.organization_id = prescribed_exercises.organization_id
        and om.user_id = auth.uid()
    )
  )
  with check (
    exists (
      select 1
      from public.organization_members om
      where om.organization_id = prescribed_exercises.organization_id
        and om.user_id = auth.uid()
    )
  );

drop policy if exists "prescribed_exercises org members delete" on public.prescribed_exercises;
create policy "prescribed_exercises org members delete"
  on public.prescribed_exercises
  for delete
  using (
    exists (
      select 1
      from public.organization_members om
      where om.organization_id = prescribed_exercises.organization_id
        and om.user_id = auth.uid()
    )
  );

drop policy if exists "workout_execution_logs org members select" on public.workout_execution_logs;
create policy "workout_execution_logs org members select"
  on public.workout_execution_logs
  for select
  using (
    exists (
      select 1
      from public.organization_members om
      where om.organization_id = workout_execution_logs.organization_id
        and om.user_id = auth.uid()
    )
  );

drop policy if exists "workout_execution_logs org members insert" on public.workout_execution_logs;
create policy "workout_execution_logs org members insert"
  on public.workout_execution_logs
  for insert
  with check (
    exists (
      select 1
      from public.organization_members om
      where om.organization_id = workout_execution_logs.organization_id
        and om.user_id = auth.uid()
    )
  );

drop policy if exists "workout_execution_logs org members update" on public.workout_execution_logs;
create policy "workout_execution_logs org members update"
  on public.workout_execution_logs
  for update
  using (
    exists (
      select 1
      from public.organization_members om
      where om.organization_id = workout_execution_logs.organization_id
        and om.user_id = auth.uid()
    )
  )
  with check (
    exists (
      select 1
      from public.organization_members om
      where om.organization_id = workout_execution_logs.organization_id
        and om.user_id = auth.uid()
    )
  );

drop policy if exists "completed_exercise_logs org members select" on public.completed_exercise_logs;
create policy "completed_exercise_logs org members select"
  on public.completed_exercise_logs
  for select
  using (
    exists (
      select 1
      from public.organization_members om
      where om.organization_id = completed_exercise_logs.organization_id
        and om.user_id = auth.uid()
    )
  );

drop policy if exists "completed_exercise_logs org members insert" on public.completed_exercise_logs;
create policy "completed_exercise_logs org members insert"
  on public.completed_exercise_logs
  for insert
  with check (
    exists (
      select 1
      from public.organization_members om
      where om.organization_id = completed_exercise_logs.organization_id
        and om.user_id = auth.uid()
    )
  );

drop policy if exists "completed_exercise_logs org members update" on public.completed_exercise_logs;
create policy "completed_exercise_logs org members update"
  on public.completed_exercise_logs
  for update
  using (
    exists (
      select 1
      from public.organization_members om
      where om.organization_id = completed_exercise_logs.organization_id
        and om.user_id = auth.uid()
    )
  )
  with check (
    exists (
      select 1
      from public.organization_members om
      where om.organization_id = completed_exercise_logs.organization_id
        and om.user_id = auth.uid()
    )
  );

drop policy if exists "completed_exercise_logs org members delete" on public.completed_exercise_logs;
create policy "completed_exercise_logs org members delete"
  on public.completed_exercise_logs
  for delete
  using (
    exists (
      select 1
      from public.organization_members om
      where om.organization_id = completed_exercise_logs.organization_id
        and om.user_id = auth.uid()
    )
  );

revoke all on table public.consultation_profiles from anon;
revoke all on table public.prescribed_workouts from anon;
revoke all on table public.prescribed_exercises from anon;
revoke all on table public.workout_execution_logs from anon;
revoke all on table public.completed_exercise_logs from anon;

grant select, insert, update, delete on table public.consultation_profiles to authenticated;
grant select, insert, update, delete on table public.prescribed_workouts to authenticated;
grant select, insert, update, delete on table public.prescribed_exercises to authenticated;
grant select, insert, update on table public.workout_execution_logs to authenticated;
grant select, insert, update, delete on table public.completed_exercise_logs to authenticated;
