export const trainerPermissionByPrefix = [
  { prefix: "/prof/students", permissionKey: "students" },
  { prefix: "/prof/classes", permissionKey: "classes" },
  { prefix: "/prof/planning", permissionKey: "training" },
  { prefix: "/prof/reports", permissionKey: "reports" },
  { prefix: "/prof/calendar", permissionKey: "calendar" },
  { prefix: "/prof/absence-notices", permissionKey: "absence_notices" },
  { prefix: "/prof/nfc-attendance", permissionKey: "classes" },
  { prefix: "/prof/exercises", permissionKey: "training" },
  { prefix: "/prof/periodization", permissionKey: "periodization" },
  { prefix: "/prof/assistant", permissionKey: "assistant" },
  { prefix: "/coord/events", permissionKey: "events" },
  { prefix: "/coord/org-members", permissionKey: "org_members" },
  { prefix: "/coord/communications", permissionKey: "org_members" },
  { prefix: "/coord/periodization", permissionKey: "periodization" },
  { prefix: "/coord/assistant", permissionKey: "assistant" },
  { prefix: "/coord/reports", permissionKey: "reports" },
  { prefix: "/coord/classes", permissionKey: "classes" },
  { prefix: "/coord/dashboard", permissionKey: "org_members" },
  { prefix: "/coord/management", permissionKey: "org_members" },
  { prefix: "/coordination", permissionKey: "org_members" },
  { prefix: "/evidence", permissionKey: "assistant" },
  { prefix: "/reports", permissionKey: "reports" },
  { prefix: "/events", permissionKey: "events" },
  { prefix: "/students", permissionKey: "students" },
  { prefix: "/class", permissionKey: "classes" },
  { prefix: "/classes", permissionKey: "classes" },
  { prefix: "/training", permissionKey: "training" },
  { prefix: "/periodization", permissionKey: "periodization" },
  { prefix: "/calendar", permissionKey: "calendar" },
  { prefix: "/absence-notices", permissionKey: "absence_notices" },
  { prefix: "/whatsapp-settings", permissionKey: "whatsapp_settings" },
  { prefix: "/assistant", permissionKey: "assistant" },
  { prefix: "/org-members", permissionKey: "org_members" },
  { prefix: "/nfc-attendance", permissionKey: "classes" },
  { prefix: "/regulation-sources", permissionKey: "org_members" },
  { prefix: "/regulation-history", permissionKey: "org_members" },
] as const;

export const studentOnlyRoutes = [
  "/absence-report",
  "/communications",
  "/student-plan",
  "/student-home",
  "/student",
];

export const trainerOnlyPrefixes = [
  "/prof",
  "/coord",
  "/coordination",
  "/evidence",
  "/absence-notices",
  "/assistant",
  "/calendar",
  "/class",
  "/classes",
  "/events",
  "/exercises",
  "/periodization",
  "/reports",
  "/org-members",
  "/regulation-history",
  "/regulation-sources",
  "/nfc-attendance",
  "/students",
  "/training",
  "/whatsapp-settings",
];

export const hybridVerificationRestrictedPrefixes = [
  "/prof",
  "/coord",
  "/coordination",
  "/org-members",
  "/reports",
  "/students",
  "/class",
  "/classes",
  "/training",
  "/periodization",
  "/calendar",
  "/events",
  "/assistant",
  "/whatsapp-settings",
  "/regulation-history",
  "/regulation-sources",
];
